# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form1_lightPJOllP.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCalendarWidget, QComboBox,
    QFrame, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit,
    QToolButton, QWidget)

class Ui_form1(object):
    def setupUi(self, form1):
        if not form1.objectName():
            form1.setObjectName(u"form1")
        form1.resize(1500, 850)
        form1.setMinimumSize(QSize(1160, 432))
        form1.setMaximumSize(QSize(1500, 850))
        self.actionINR = QAction(form1)
        self.actionINR.setObjectName(u"actionINR")
        self.actionOpen = QAction(form1)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(form1)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(form1)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionExit = QAction(form1)
        self.actionExit.setObjectName(u"actionExit")
        self.action_screenshot = QAction(form1)
        self.action_screenshot.setObjectName(u"action_screenshot")
        self.actionTable_Edit = QAction(form1)
        self.actionTable_Edit.setObjectName(u"actionTable_Edit")
        self.actionAs_CSV_Excel = QAction(form1)
        self.actionAs_CSV_Excel.setObjectName(u"actionAs_CSV_Excel")
        self.actionOpen_Directories = QAction(form1)
        self.actionOpen_Directories.setObjectName(u"actionOpen_Directories")
        self.actionLight = QAction(form1)
        self.actionLight.setObjectName(u"actionLight")
        self.actionDakr = QAction(form1)
        self.actionDakr.setObjectName(u"actionDakr")
        self.actionUSD = QAction(form1)
        self.actionUSD.setObjectName(u"actionUSD")
        self.actionClear_Data = QAction(form1)
        self.actionClear_Data.setObjectName(u"actionClear_Data")
        self.actionRefresh = QAction(form1)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.actionInfo = QAction(form1)
        self.actionInfo.setObjectName(u"actionInfo")
        self.centralwidget = QWidget(form1)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 1500, 820))
        self.label.setStyleSheet(u"background-color: rgb(184, 184, 184);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(1160, 9, 331, 219))
        self.tabWidget.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget.setDocumentMode(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.widget = QWidget(self.tab)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 371, 221))
        self.widget.setStyleSheet(u"background-color: rgb(38, 38, 38);")
        self.calendarWidget = QCalendarWidget(self.widget)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(0, 0, 331, 201))
        self.calendarWidget.setStyleSheet(u"background-color: rgb(221, 221, 221);\n"
"font: 11pt \"Segoe UI\";\n"
"color: rgb(49, 77, 107);\n"
"border-color: rgb(95, 95, 95);\n"
"selection-color: rgb(248, 248, 248);\n"
"gridline-color: rgb(111, 111, 111);\n"
"selection-background-color: rgb(126, 126, 126);")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.textEdit_notes = QTextEdit(self.tab_2)
        self.textEdit_notes.setObjectName(u"textEdit_notes")
        self.textEdit_notes.setGeometry(QRect(0, 0, 331, 203))
        font = QFont()
        font.setPointSize(14)
        self.textEdit_notes.setFont(font)
        self.textEdit_notes.setAutoFillBackground(False)
        self.textEdit_notes.setFrameShape(QFrame.Shape.NoFrame)
        self.textEdit_notes.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.textEdit_notes.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextBrowserInteraction|Qt.TextInteractionFlag.TextEditable|Qt.TextInteractionFlag.TextEditorInteraction|Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget_5 = QWidget(self.centralwidget)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(12, 35, 1140, 360))
        self.widget_5.setStyleSheet(u"background-color: rgb(154, 154, 154);")
        self.label_expense_record = QLabel(self.widget_5)
        self.label_expense_record.setObjectName(u"label_expense_record")
        self.label_expense_record.setGeometry(QRect(14, -4, 181, 31))
        self.label_expense_record.setFont(font)
        self.label_total_expense = QLabel(self.widget_5)
        self.label_total_expense.setObjectName(u"label_total_expense")
        self.label_total_expense.setGeometry(QRect(740, 325, 231, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.label_total_expense.setFont(font1)
        self.label_total_spends = QLabel(self.widget_5)
        self.label_total_spends.setObjectName(u"label_total_spends")
        self.label_total_spends.setGeometry(QRect(972, 331, 151, 21))
        self.label_total_spends.setFont(font1)
        self.tableWidget_1 = QTableWidget(self.widget_5)
        if (self.tableWidget_1.columnCount() < 10):
            self.tableWidget_1.setColumnCount(10)
        font2 = QFont()
        font2.setPointSize(9)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font2);
        self.tableWidget_1.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        if (self.tableWidget_1.rowCount() < 9):
            self.tableWidget_1.setRowCount(9)
        self.tableWidget_1.setObjectName(u"tableWidget_1")
        self.tableWidget_1.setGeometry(QRect(10, 27, 1121, 301))
        self.tableWidget_1.setFont(font1)
        self.tableWidget_1.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.tableWidget_1.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget_1.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_1.setLineWidth(1)
        self.tableWidget_1.setMidLineWidth(0)
        self.tableWidget_1.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget_1.setAlternatingRowColors(True)
        self.tableWidget_1.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableWidget_1.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_1.setTextElideMode(Qt.TextElideMode.ElideMiddle)
        self.tableWidget_1.setShowGrid(True)
        self.tableWidget_1.setGridStyle(Qt.PenStyle.DashLine)
        self.tableWidget_1.setSortingEnabled(False)
        self.tableWidget_1.setRowCount(9)
        self.tableWidget_1.setColumnCount(10)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1.horizontalHeader().setMinimumSectionSize(41)
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_1.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_1.verticalHeader().setStretchLastSection(False)
        self.lineEdit_spend = QLineEdit(self.widget_5)
        self.lineEdit_spend.setObjectName(u"lineEdit_spend")
        self.lineEdit_spend.setGeometry(QRect(12, 331, 121, 25))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_spend.sizePolicy().hasHeightForWidth())
        self.lineEdit_spend.setSizePolicy(sizePolicy)
        self.lineEdit_spend.setMinimumSize(QSize(0, 0))
        self.lineEdit_spend.setMaximumSize(QSize(1920, 70))
        self.lineEdit_spend.setFont(font)
        self.lineEdit_spend.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_spend.setStyleSheet(u"background-color: rgb(175, 198, 217);")
        self.lineEdit_spend.setMaxLength(1000)
        self.lineEdit_spend.setFrame(False)
        self.lineEdit_spend.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_spend.setCursorPosition(0)
        self.lineEdit_spend.setDragEnabled(True)
        self.lineEdit_spend.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_spend.setClearButtonEnabled(False)
        self.toolButton_save1 = QToolButton(self.widget_5)
        self.toolButton_save1.setObjectName(u"toolButton_save1")
        self.toolButton_save1.setGeometry(QRect(670, 329, 61, 26))
        font3 = QFont()
        font3.setPointSize(12)
        self.toolButton_save1.setFont(font3)
        self.lineEdit_item = QLineEdit(self.widget_5)
        self.lineEdit_item.setObjectName(u"lineEdit_item")
        self.lineEdit_item.setGeometry(QRect(137, 331, 111, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_item.sizePolicy().hasHeightForWidth())
        self.lineEdit_item.setSizePolicy(sizePolicy)
        self.lineEdit_item.setMinimumSize(QSize(0, 0))
        self.lineEdit_item.setMaximumSize(QSize(1920, 70))
        self.lineEdit_item.setFont(font)
        self.lineEdit_item.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_item.setStyleSheet(u"background-color: rgb(175, 198, 217);")
        self.lineEdit_item.setMaxLength(1000)
        self.lineEdit_item.setFrame(False)
        self.lineEdit_item.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_item.setCursorPosition(0)
        self.lineEdit_item.setDragEnabled(True)
        self.lineEdit_item.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_item.setClearButtonEnabled(False)
        self.lineEdit_reciepent = QLineEdit(self.widget_5)
        self.lineEdit_reciepent.setObjectName(u"lineEdit_reciepent")
        self.lineEdit_reciepent.setGeometry(QRect(253, 331, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_reciepent.sizePolicy().hasHeightForWidth())
        self.lineEdit_reciepent.setSizePolicy(sizePolicy)
        self.lineEdit_reciepent.setMinimumSize(QSize(0, 0))
        self.lineEdit_reciepent.setMaximumSize(QSize(1920, 70))
        self.lineEdit_reciepent.setFont(font)
        self.lineEdit_reciepent.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_reciepent.setStyleSheet(u"background-color: rgb(175, 198, 217);")
        self.lineEdit_reciepent.setMaxLength(1000)
        self.lineEdit_reciepent.setFrame(False)
        self.lineEdit_reciepent.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_reciepent.setCursorPosition(0)
        self.lineEdit_reciepent.setDragEnabled(True)
        self.lineEdit_reciepent.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_reciepent.setClearButtonEnabled(False)
        self.toolButton_del_row = QToolButton(self.widget_5)
        self.toolButton_del_row.setObjectName(u"toolButton_del_row")
        self.toolButton_del_row.setGeometry(QRect(1100, 1, 31, 26))
        font4 = QFont()
        font4.setPointSize(20)
        self.toolButton_del_row.setFont(font4)
        self.toolButton_del_row.setStyleSheet(u"background-color: rgb(22, 22, 22);\n"
"color: rgb(255, 0, 0);")
        self.label_expense_record.raise_()
        self.label_total_expense.raise_()
        self.label_total_spends.raise_()
        self.lineEdit_spend.raise_()
        self.toolButton_save1.raise_()
        self.lineEdit_item.raise_()
        self.lineEdit_reciepent.raise_()
        self.toolButton_del_row.raise_()
        self.tableWidget_1.raise_()
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(16, -1, 161, 31))
        self.label_13.setFont(font1)
        self.label_13.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(1160, 238, 331, 321))
        self.textEdit.setStyleSheet(u"background-color: rgb(140, 140, 140);")
        self.textEdit.setFrameShape(QFrame.Shape.NoFrame)
        self.textEdit.setLineWidth(0)
        self.textEdit.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.label_name = QLabel(self.centralwidget)
        self.label_name.setObjectName(u"label_name")
        self.label_name.setGeometry(QRect(1360, 360, 131, 51))
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(True)
        self.label_name.setFont(font5)
        self.label_name.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.label_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_name.setWordWrap(True)
        self.label_income = QLabel(self.centralwidget)
        self.label_income.setObjectName(u"label_income")
        self.label_income.setGeometry(QRect(1274, 286, 108, 20))
        self.label_income.setFont(font5)
        self.label_income.setStyleSheet(u"color: rgb(175, 198, 217);")
        self.label_expense = QLabel(self.centralwidget)
        self.label_expense.setObjectName(u"label_expense")
        self.label_expense.setGeometry(QRect(1274, 306, 108, 20))
        self.label_expense.setFont(font5)
        self.label_expense.setStyleSheet(u"color: rgb(175, 198, 217);")
        self.label_savings = QLabel(self.centralwidget)
        self.label_savings.setObjectName(u"label_savings")
        self.label_savings.setGeometry(QRect(1274, 326, 108, 20))
        self.label_savings.setFont(font5)
        self.label_savings.setStyleSheet(u"color: rgb(175, 198, 217);")
        self.label_gains = QLabel(self.centralwidget)
        self.label_gains.setObjectName(u"label_gains")
        self.label_gains.setGeometry(QRect(1274, 346, 108, 20))
        self.label_gains.setFont(font5)
        self.label_gains.setStyleSheet(u"color: rgb(175, 198, 217);")
        self.widget_6 = QWidget(self.centralwidget)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(12, 432, 1140, 374))
        self.widget_6.setStyleSheet(u"background-color: rgb(154, 154, 154);")
        self.label_extra_gains = QLabel(self.widget_6)
        self.label_extra_gains.setObjectName(u"label_extra_gains")
        self.label_extra_gains.setGeometry(QRect(14, -4, 111, 31))
        self.label_extra_gains.setFont(font)
        self.label_monthly_gains = QLabel(self.widget_6)
        self.label_monthly_gains.setObjectName(u"label_monthly_gains")
        self.label_monthly_gains.setGeometry(QRect(740, 335, 201, 31))
        self.label_monthly_gains.setFont(font1)
        self.label_total_gains = QLabel(self.widget_6)
        self.label_total_gains.setObjectName(u"label_total_gains")
        self.label_total_gains.setGeometry(QRect(950, 340, 171, 21))
        self.label_total_gains.setFont(font1)
        self.tableWidget_2 = QTableWidget(self.widget_6)
        if (self.tableWidget_2.columnCount() < 10):
            self.tableWidget_2.setColumnCount(10)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font2);
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, __qtablewidgetitem13)
        if (self.tableWidget_2.rowCount() < 12):
            self.tableWidget_2.setRowCount(12)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(10, 27, 1121, 306))
        self.tableWidget_2.setFont(font1)
        self.tableWidget_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tableWidget_2.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.tableWidget_2.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget_2.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setMidLineWidth(0)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(Qt.PenStyle.DashLine)
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setRowCount(12)
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(41)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.lineEdit_get = QLineEdit(self.widget_6)
        self.lineEdit_get.setObjectName(u"lineEdit_get")
        self.lineEdit_get.setGeometry(QRect(12, 341, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_get.sizePolicy().hasHeightForWidth())
        self.lineEdit_get.setSizePolicy(sizePolicy)
        self.lineEdit_get.setMinimumSize(QSize(0, 0))
        self.lineEdit_get.setMaximumSize(QSize(1920, 70))
        self.lineEdit_get.setFont(font)
        self.lineEdit_get.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_get.setStyleSheet(u"background-color: rgb(174, 197, 216);")
        self.lineEdit_get.setMaxLength(1000)
        self.lineEdit_get.setFrame(False)
        self.lineEdit_get.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_get.setCursorPosition(0)
        self.lineEdit_get.setDragEnabled(True)
        self.lineEdit_get.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_get.setClearButtonEnabled(False)
        self.toolButton_save2 = QToolButton(self.widget_6)
        self.toolButton_save2.setObjectName(u"toolButton_save2")
        self.toolButton_save2.setGeometry(QRect(670, 339, 61, 26))
        self.toolButton_save2.setFont(font3)
        self.lineEdit_for_what = QLineEdit(self.widget_6)
        self.lineEdit_for_what.setObjectName(u"lineEdit_for_what")
        self.lineEdit_for_what.setGeometry(QRect(137, 341, 111, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_for_what.sizePolicy().hasHeightForWidth())
        self.lineEdit_for_what.setSizePolicy(sizePolicy)
        self.lineEdit_for_what.setMinimumSize(QSize(0, 0))
        self.lineEdit_for_what.setMaximumSize(QSize(1920, 70))
        self.lineEdit_for_what.setFont(font)
        self.lineEdit_for_what.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_for_what.setStyleSheet(u"background-color: rgb(174, 197, 216);")
        self.lineEdit_for_what.setMaxLength(1000)
        self.lineEdit_for_what.setFrame(False)
        self.lineEdit_for_what.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_for_what.setCursorPosition(0)
        self.lineEdit_for_what.setDragEnabled(True)
        self.lineEdit_for_what.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_for_what.setClearButtonEnabled(False)
        self.lineEdit_giver = QLineEdit(self.widget_6)
        self.lineEdit_giver.setObjectName(u"lineEdit_giver")
        self.lineEdit_giver.setGeometry(QRect(253, 341, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_giver.sizePolicy().hasHeightForWidth())
        self.lineEdit_giver.setSizePolicy(sizePolicy)
        self.lineEdit_giver.setMinimumSize(QSize(0, 0))
        self.lineEdit_giver.setMaximumSize(QSize(1920, 70))
        self.lineEdit_giver.setFont(font)
        self.lineEdit_giver.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_giver.setStyleSheet(u"background-color: rgb(174, 197, 216);")
        self.lineEdit_giver.setMaxLength(1000)
        self.lineEdit_giver.setFrame(False)
        self.lineEdit_giver.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_giver.setCursorPosition(0)
        self.lineEdit_giver.setDragEnabled(True)
        self.lineEdit_giver.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_giver.setClearButtonEnabled(False)
        self.toolButton_del_row_2 = QToolButton(self.widget_6)
        self.toolButton_del_row_2.setObjectName(u"toolButton_del_row_2")
        self.toolButton_del_row_2.setGeometry(QRect(1100, 0, 31, 26))
        self.toolButton_del_row_2.setFont(font4)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1400, 280, 70, 70))
        self.label_2.setPixmap(QPixmap(u"pprofile2.png"))
        self.label_2.setScaledContents(True)
        self.lineEdit_income = QLineEdit(self.centralwidget)
        self.lineEdit_income.setObjectName(u"lineEdit_income")
        self.lineEdit_income.setGeometry(QRect(518, 5, 161, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_income.sizePolicy().hasHeightForWidth())
        self.lineEdit_income.setSizePolicy(sizePolicy)
        self.lineEdit_income.setMinimumSize(QSize(0, 0))
        self.lineEdit_income.setMaximumSize(QSize(1920, 70))
        font6 = QFont()
        font6.setPointSize(14)
        font6.setBold(True)
        self.lineEdit_income.setFont(font6)
        self.lineEdit_income.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_income.setMaxLength(1000)
        self.lineEdit_income.setFrame(False)
        self.lineEdit_income.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_income.setCursorPosition(1)
        self.lineEdit_income.setDragEnabled(True)
        self.lineEdit_income.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_income.setClearButtonEnabled(False)
        self.comboBox_3 = QComboBox(self.centralwidget)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(1029, 2, 101, 30))
        self.comboBox_3.setFont(font3)
        self.comboBox_3.setFrame(False)
        self.lineEdit_calc = QLineEdit(self.centralwidget)
        self.lineEdit_calc.setObjectName(u"lineEdit_calc")
        self.lineEdit_calc.setGeometry(QRect(931, 401, 221, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_calc.sizePolicy().hasHeightForWidth())
        self.lineEdit_calc.setSizePolicy(sizePolicy)
        self.lineEdit_calc.setMinimumSize(QSize(0, 0))
        self.lineEdit_calc.setMaximumSize(QSize(1920, 70))
        self.lineEdit_calc.setFont(font6)
        self.lineEdit_calc.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_calc.setMaxLength(1000)
        self.lineEdit_calc.setFrame(False)
        self.lineEdit_calc.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_calc.setCursorPosition(0)
        self.lineEdit_calc.setDragEnabled(True)
        self.lineEdit_calc.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_calc.setClearButtonEnabled(False)
        self.label_calc = QLabel(self.centralwidget)
        self.label_calc.setObjectName(u"label_calc")
        self.label_calc.setGeometry(QRect(696, 397, 231, 31))
        self.label_calc.setFont(font1)
        self.label_calc.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.label_calc.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(356, -1, 161, 31))
        self.label_14.setFont(font1)
        self.label_14.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_income0 = QLineEdit(self.centralwidget)
        self.lineEdit_income0.setObjectName(u"lineEdit_income0")
        self.lineEdit_income0.setGeometry(QRect(183, 5, 161, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_income0.sizePolicy().hasHeightForWidth())
        self.lineEdit_income0.setSizePolicy(sizePolicy)
        self.lineEdit_income0.setMinimumSize(QSize(0, 0))
        self.lineEdit_income0.setMaximumSize(QSize(1920, 70))
        self.lineEdit_income0.setFont(font6)
        self.lineEdit_income0.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_income0.setMaxLength(1000)
        self.lineEdit_income0.setFrame(False)
        self.lineEdit_income0.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_income0.setCursorPosition(1)
        self.lineEdit_income0.setDragEnabled(True)
        self.lineEdit_income0.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_income0.setClearButtonEnabled(False)
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(1160, 567, 331, 238))
        self.tabWidget_2.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget_2.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget_2.setDocumentMode(True)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.widget_graph = QWidget(self.tab_5)
        self.widget_graph.setObjectName(u"widget_graph")
        self.widget_graph.setGeometry(QRect(0, -10, 331, 238))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.widget_graph_2 = QWidget(self.tab_6)
        self.widget_graph_2.setObjectName(u"widget_graph_2")
        self.widget_graph_2.setGeometry(QRect(0, 0, 331, 241))
        self.widget_graph_2.setStyleSheet(u"background-color: rgb(28, 28, 28);")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.toolButton_expand = QToolButton(self.centralwidget)
        self.toolButton_expand.setObjectName(u"toolButton_expand")
        self.toolButton_expand.setGeometry(QRect(960, 4, 61, 26))
        self.toolButton_expand.setFont(font3)
        self.label_date = QLabel(self.centralwidget)
        self.label_date.setObjectName(u"label_date")
        self.label_date.setGeometry(QRect(30, 397, 181, 31))
        self.label_date.setFont(font1)
        self.label_date.setStyleSheet(u"color: rgb(107, 139, 255);")
        self.comboBox_4 = QComboBox(self.centralwidget)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(682, 2, 191, 30))
        self.comboBox_4.setFont(font3)
        self.comboBox_4.setFrame(False)
        form1.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.tabWidget.raise_()
        self.widget_5.raise_()
        self.textEdit.raise_()
        self.label_name.raise_()
        self.label_income.raise_()
        self.label_expense.raise_()
        self.label_savings.raise_()
        self.label_gains.raise_()
        self.widget_6.raise_()
        self.label_2.raise_()
        self.comboBox_3.raise_()
        self.lineEdit_calc.raise_()
        self.label_calc.raise_()
        self.tabWidget_2.raise_()
        self.toolButton_expand.raise_()
        self.label_date.raise_()
        self.label_13.raise_()
        self.lineEdit_income0.raise_()
        self.label_14.raise_()
        self.lineEdit_income.raise_()
        self.comboBox_4.raise_()
        self.menubar = QMenuBar(form1)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1500, 33))
        self.menubar.setFont(font1)
        self.menubar.setStyleSheet(u"background-color: rgb(175, 198, 217);\n"
"border-color: rgb(130, 255, 213);\n"
"alternate-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(98, 255, 156);\n"
"selection-background-color: rgb(49, 49, 49);\n"
"gridline-color: rgb(97, 46, 46);\n"
"color: rgb(0, 0, 0);")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuExport = QMenu(self.menubar)
        self.menuExport.setObjectName(u"menuExport")
        self.menuSnap = QMenu(self.menubar)
        self.menuSnap.setObjectName(u"menuSnap")
        self.menuDark = QMenu(self.menubar)
        self.menuDark.setObjectName(u"menuDark")
        self.menuCurrency = QMenu(self.menubar)
        self.menuCurrency.setObjectName(u"menuCurrency")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setFont(font3)
        self.menuCreate = QMenu(self.menubar)
        self.menuCreate.setObjectName(u"menuCreate")
        form1.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuSnap.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuDark.menuAction())
        self.menubar.addAction(self.menuCurrency.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionTable_Edit)
        self.menuEdit.addAction(self.actionClear_Data)
        self.menuExport.addAction(self.actionAs_CSV_Excel)
        self.menuSnap.addSeparator()
        self.menuSnap.addAction(self.action_screenshot)
        self.menuSnap.addAction(self.actionOpen_Directories)
        self.menuDark.addAction(self.actionLight)
        self.menuDark.addAction(self.actionDakr)
        self.menuCurrency.addAction(self.actionINR)
        self.menuCurrency.addAction(self.actionUSD)
        self.menuAbout.addAction(self.actionInfo)

        self.retranslateUi(form1)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(form1)
    # setupUi

    def retranslateUi(self, form1):
        form1.setWindowTitle(QCoreApplication.translate("form1", u"Finance Flow v1.1", None))
        self.actionINR.setText(QCoreApplication.translate("form1", u"INR", None))
        self.actionOpen.setText(QCoreApplication.translate("form1", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("form1", u"Save Settings", None))
        self.actionSave_As.setText(QCoreApplication.translate("form1", u"Save Notes", None))
        self.actionExit.setText(QCoreApplication.translate("form1", u"Exit", None))
        self.action_screenshot.setText(QCoreApplication.translate("form1", u"ScreenShot", None))
        self.actionTable_Edit.setText(QCoreApplication.translate("form1", u"Table Edit", None))
        self.actionAs_CSV_Excel.setText(QCoreApplication.translate("form1", u"As CSV/Excel", None))
        self.actionOpen_Directories.setText(QCoreApplication.translate("form1", u"Open Directory", None))
        self.actionLight.setText(QCoreApplication.translate("form1", u"Light", None))
        self.actionDakr.setText(QCoreApplication.translate("form1", u"Dark", None))
        self.actionUSD.setText(QCoreApplication.translate("form1", u"USD", None))
        self.actionClear_Data.setText(QCoreApplication.translate("form1", u"Reset Data", None))
        self.actionRefresh.setText(QCoreApplication.translate("form1", u"Refresh", None))
        self.actionInfo.setText(QCoreApplication.translate("form1", u"Info", None))
        self.label.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("form1", u"Calender", None))
        self.textEdit_notes.setHtml(QCoreApplication.translate("form1", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit_notes.setPlaceholderText(QCoreApplication.translate("form1", u"Type or Just Drag and Drop the websites content here...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("form1", u"Notes", None))
        self.label_expense_record.setText(QCoreApplication.translate("form1", u"Purchases :-", None))
        self.label_total_expense.setText(QCoreApplication.translate("form1", u"Total monthly Spend = ", None))
        self.label_total_spends.setText(QCoreApplication.translate("form1", u"0", None))
        ___qtablewidgetitem = self.tableWidget_1.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("form1", u"SPEND/-", None));
        ___qtablewidgetitem1 = self.tableWidget_1.horizontalHeaderItem(2)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("form1", u"Item/Purpose", None));
        ___qtablewidgetitem2 = self.tableWidget_1.horizontalHeaderItem(4)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("form1", u"Reciepent", None));
        ___qtablewidgetitem3 = self.tableWidget_1.horizontalHeaderItem(6)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("form1", u"Time", None));
        self.lineEdit_spend.setText("")
        self.lineEdit_spend.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.toolButton_save1.setText(QCoreApplication.translate("form1", u"Save", None))
        self.lineEdit_item.setText("")
        self.lineEdit_item.setPlaceholderText(QCoreApplication.translate("form1", u"Item...", None))
        self.lineEdit_reciepent.setText("")
        self.lineEdit_reciepent.setPlaceholderText(QCoreApplication.translate("form1", u"Recipient..", None))
        self.toolButton_del_row.setText(QCoreApplication.translate("form1", u"-", None))
        self.label_13.setText(QCoreApplication.translate("form1", u"Monthly Income:", None))
        self.textEdit.setHtml(QCoreApplication.translate("form1", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#f8f8f8;\"># Monthly Summary Report</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; col"
                        "or:#000000;\">1. Total Income</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">2. Total Expense</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">3. Net Savings</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">4. Extra Gains</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">5. Miscellaneous Expense</span></p></body></html>", None))
        self.label_name.setText(QCoreApplication.translate("form1", u"Abhishek Verma", None))
        self.label_income.setText(QCoreApplication.translate("form1", u"64000/-", None))
        self.label_expense.setText(QCoreApplication.translate("form1", u"45000", None))
        self.label_savings.setText(QCoreApplication.translate("form1", u"15000", None))
        self.label_gains.setText(QCoreApplication.translate("form1", u"4000", None))
        self.label_extra_gains.setText(QCoreApplication.translate("form1", u"Sales:-", None))
        self.label_monthly_gains.setText(QCoreApplication.translate("form1", u"Total monthly Sales = ", None))
        self.label_total_gains.setText(QCoreApplication.translate("form1", u"1600/-", None))
        ___qtablewidgetitem4 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("form1", u"RECIEVED/-", None));
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("form1", u"Item/N/A", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("form1", u"Payer/Giver", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(6)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("form1", u"Time", None));
        self.lineEdit_get.setText("")
        self.lineEdit_get.setPlaceholderText(QCoreApplication.translate("form1", u"Get/-", None))
        self.toolButton_save2.setText(QCoreApplication.translate("form1", u"Save", None))
        self.lineEdit_for_what.setText("")
        self.lineEdit_for_what.setPlaceholderText(QCoreApplication.translate("form1", u"for what...", None))
        self.lineEdit_giver.setText("")
        self.lineEdit_giver.setPlaceholderText(QCoreApplication.translate("form1", u"Giver...", None))
        self.toolButton_del_row_2.setText(QCoreApplication.translate("form1", u"-", None))
        self.label_2.setText("")
        self.lineEdit_income.setText(QCoreApplication.translate("form1", u"0", None))
        self.lineEdit_income.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("form1", u"GST-Auto", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("form1", u"0% GST", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("form1", u"5% GST", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("form1", u"12% GST", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("form1", u"18% GST", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("form1", u"28% GST", None))

        self.lineEdit_calc.setText("")
        self.lineEdit_calc.setPlaceholderText(QCoreApplication.translate("form1", u"Use Numkeys...", None))
        self.label_calc.setText(QCoreApplication.translate("form1", u"Calc :", None))
        self.label_14.setText(QCoreApplication.translate("form1", u"Current Income:", None))
        self.lineEdit_income0.setText(QCoreApplication.translate("form1", u"0", None))
        self.lineEdit_income0.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("form1", u"Remaining income", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("form1", u"Extra Gains", None))
        self.toolButton_expand.setText(QCoreApplication.translate("form1", u"Layout", None))
        self.label_date.setText(QCoreApplication.translate("form1", u"Date:- 26/01/2001", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("form1", u"Default WorkSpace", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("form1", u"Sales", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("form1", u"Purchase", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("form1", u"Stock", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("form1", u"Banking Transactions", None))

        self.menuFile.setTitle(QCoreApplication.translate("form1", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("form1", u"Edit", None))
        self.menuExport.setTitle(QCoreApplication.translate("form1", u"Export", None))
        self.menuSnap.setTitle(QCoreApplication.translate("form1", u"Snap", None))
        self.menuDark.setTitle(QCoreApplication.translate("form1", u"Theme", None))
        self.menuCurrency.setTitle(QCoreApplication.translate("form1", u"Currency", None))
        self.menuHelp.setTitle(QCoreApplication.translate("form1", u"Help", None))
        self.menuAbout.setTitle(QCoreApplication.translate("form1", u"About", None))
        self.menuCreate.setTitle(QCoreApplication.translate("form1", u"Create", None))
    # retranslateUi

