# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form1RiGXxJ.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCalendarWidget, QComboBox,
    QFrame, QHeaderView, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPushButton, QScrollArea, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit,
    QToolButton, QWidget)

class Ui_form1(object):
    def setupUi(self, form1):
        if not form1.objectName():
            form1.setObjectName(u"form1")
        form1.resize(1500, 850)
        form1.setMinimumSize(QSize(1160, 432))
        form1.setMaximumSize(QSize(1500, 850))
        self.actionINR = QAction(form1)
        self.actionINR.setObjectName(u"actionINR")
        self.actionOpen = QAction(form1)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(form1)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(form1)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionExit = QAction(form1)
        self.actionExit.setObjectName(u"actionExit")
        self.action_screenshot = QAction(form1)
        self.action_screenshot.setObjectName(u"action_screenshot")
        self.actionTable_Edit = QAction(form1)
        self.actionTable_Edit.setObjectName(u"actionTable_Edit")
        self.actionAs_CSV_Excel = QAction(form1)
        self.actionAs_CSV_Excel.setObjectName(u"actionAs_CSV_Excel")
        self.actionOpen_Directories = QAction(form1)
        self.actionOpen_Directories.setObjectName(u"actionOpen_Directories")
        self.actionLight = QAction(form1)
        self.actionLight.setObjectName(u"actionLight")
        self.actionDakr = QAction(form1)
        self.actionDakr.setObjectName(u"actionDakr")
        self.actionUSD = QAction(form1)
        self.actionUSD.setObjectName(u"actionUSD")
        self.actionClear_Data = QAction(form1)
        self.actionClear_Data.setObjectName(u"actionClear_Data")
        self.actionRefresh = QAction(form1)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.actionInfo = QAction(form1)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionArrange = QAction(form1)
        self.actionArrange.setObjectName(u"actionArrange")
        self.centralwidget = QWidget(form1)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 1500, 820))
        self.label.setStyleSheet(u"\n"
"background-color: rgb(165, 187, 230);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(1160, 39, 331, 241))
        self.tabWidget.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget.setDocumentMode(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.widget = QWidget(self.tab)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 371, 228))
        self.widget.setStyleSheet(u"background-color: rgb(38, 38, 38);")
        self.calendarWidget = QCalendarWidget(self.widget)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(0, 0, 331, 222))
        self.calendarWidget.setStyleSheet(u"background-color: rgb(221, 221, 221);\n"
"font: 11pt \"Segoe UI\";\n"
"color: rgb(49, 77, 107);\n"
"border-color: rgb(95, 95, 95);\n"
"selection-color: rgb(248, 248, 248);\n"
"gridline-color: rgb(111, 111, 111);\n"
"selection-background-color: rgb(126, 126, 126);")
        self.calendarWidget.setFirstDayOfWeek(Qt.DayOfWeek.Monday)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QCalendarWidget.SelectionMode.SingleSelection)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.textEdit_notes = QTextEdit(self.tab_2)
        self.textEdit_notes.setObjectName(u"textEdit_notes")
        self.textEdit_notes.setGeometry(QRect(0, 0, 331, 224))
        font = QFont()
        font.setPointSize(14)
        self.textEdit_notes.setFont(font)
        self.textEdit_notes.setAutoFillBackground(False)
        self.textEdit_notes.setStyleSheet(u"background-color: rgb(228, 235, 248);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_notes.setFrameShape(QFrame.Shape.NoFrame)
        self.textEdit_notes.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.textEdit_notes.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextBrowserInteraction|Qt.TextInteractionFlag.TextEditable|Qt.TextInteractionFlag.TextEditorInteraction|Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(12, 1, 141, 31))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(1160, 287, 331, 273))
        self.textEdit.setStyleSheet(u"color: rgb(244, 244, 244);")
        self.textEdit.setFrameShape(QFrame.Shape.NoFrame)
        self.textEdit.setLineWidth(0)
        self.textEdit.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.label_name = QLabel(self.centralwidget)
        self.label_name.setObjectName(u"label_name")
        self.label_name.setGeometry(QRect(1360, 407, 131, 51))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_name.setFont(font1)
        self.label_name.setStyleSheet(u"")
        self.label_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_name.setWordWrap(True)
        self.label_income = QLabel(self.centralwidget)
        self.label_income.setObjectName(u"label_income")
        self.label_income.setGeometry(QRect(1274, 333, 108, 20))
        self.label_income.setFont(font1)
        self.label_expense = QLabel(self.centralwidget)
        self.label_expense.setObjectName(u"label_expense")
        self.label_expense.setGeometry(QRect(1274, 353, 108, 20))
        self.label_expense.setFont(font1)
        self.label_savings = QLabel(self.centralwidget)
        self.label_savings.setObjectName(u"label_savings")
        self.label_savings.setGeometry(QRect(1274, 373, 108, 20))
        self.label_savings.setFont(font1)
        self.label_savings.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_gains = QLabel(self.centralwidget)
        self.label_gains.setObjectName(u"label_gains")
        self.label_gains.setGeometry(QRect(1274, 393, 108, 20))
        self.label_gains.setFont(font1)
        self.label_gains.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1400, 327, 70, 70))
        self.label_2.setPixmap(QPixmap(u"../../../../Users/Abhishek/.designer/template/pprofile2.png"))
        self.label_2.setScaledContents(True)
        self.lineEdit_income = QLineEdit(self.centralwidget)
        self.lineEdit_income.setObjectName(u"lineEdit_income")
        self.lineEdit_income.setGeometry(QRect(465, 5, 161, 25))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_income.sizePolicy().hasHeightForWidth())
        self.lineEdit_income.setSizePolicy(sizePolicy)
        self.lineEdit_income.setMinimumSize(QSize(0, 0))
        self.lineEdit_income.setMaximumSize(QSize(1920, 70))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        self.lineEdit_income.setFont(font2)
        self.lineEdit_income.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_income.setStyleSheet(u"")
        self.lineEdit_income.setMaxLength(1000)
        self.lineEdit_income.setFrame(False)
        self.lineEdit_income.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_income.setCursorPosition(1)
        self.lineEdit_income.setDragEnabled(True)
        self.lineEdit_income.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_income.setClearButtonEnabled(False)
        self.comboBox_3 = QComboBox(self.centralwidget)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(815, 3, 111, 30))
        font3 = QFont()
        font3.setPointSize(12)
        self.comboBox_3.setFont(font3)
        self.comboBox_3.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.comboBox_3.setFrame(False)
        self.lineEdit_calc = QLineEdit(self.centralwidget)
        self.lineEdit_calc.setObjectName(u"lineEdit_calc")
        self.lineEdit_calc.setGeometry(QRect(1340, 4, 151, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_calc.sizePolicy().hasHeightForWidth())
        self.lineEdit_calc.setSizePolicy(sizePolicy)
        self.lineEdit_calc.setMinimumSize(QSize(0, 0))
        self.lineEdit_calc.setMaximumSize(QSize(1920, 70))
        self.lineEdit_calc.setFont(font2)
        self.lineEdit_calc.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_calc.setStyleSheet(u"")
        self.lineEdit_calc.setMaxLength(1000)
        self.lineEdit_calc.setFrame(False)
        self.lineEdit_calc.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_calc.setCursorPosition(0)
        self.lineEdit_calc.setDragEnabled(True)
        self.lineEdit_calc.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_calc.setClearButtonEnabled(False)
        self.label_calc = QLabel(self.centralwidget)
        self.label_calc.setObjectName(u"label_calc")
        self.label_calc.setGeometry(QRect(1157, 0, 181, 30))
        self.label_calc.setFont(font)
        self.label_calc.setStyleSheet(u"")
        self.label_calc.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(325, 1, 141, 31))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"")
        self.lineEdit_income0 = QLineEdit(self.centralwidget)
        self.lineEdit_income0.setObjectName(u"lineEdit_income0")
        self.lineEdit_income0.setGeometry(QRect(158, 5, 161, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_income0.sizePolicy().hasHeightForWidth())
        self.lineEdit_income0.setSizePolicy(sizePolicy)
        self.lineEdit_income0.setMinimumSize(QSize(0, 0))
        self.lineEdit_income0.setMaximumSize(QSize(1920, 70))
        self.lineEdit_income0.setFont(font2)
        self.lineEdit_income0.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_income0.setStyleSheet(u"")
        self.lineEdit_income0.setMaxLength(1000)
        self.lineEdit_income0.setFrame(False)
        self.lineEdit_income0.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_income0.setCursorPosition(1)
        self.lineEdit_income0.setDragEnabled(True)
        self.lineEdit_income0.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_income0.setClearButtonEnabled(False)
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(1160, 567, 331, 238))
        self.tabWidget_2.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget_2.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget_2.setDocumentMode(True)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.widget_graph = QWidget(self.tab_5)
        self.widget_graph.setObjectName(u"widget_graph")
        self.widget_graph.setGeometry(QRect(0, -10, 331, 238))
        self.widget_graph.setStyleSheet(u"background-color: rgb(228, 235, 248);")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.widget_graph_2 = QWidget(self.tab_6)
        self.widget_graph_2.setObjectName(u"widget_graph_2")
        self.widget_graph_2.setGeometry(QRect(0, 0, 331, 241))
        self.widget_graph_2.setStyleSheet(u"background-color: rgb(228, 235, 248);")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.toolButton_expand = QToolButton(self.centralwidget)
        self.toolButton_expand.setObjectName(u"toolButton_expand")
        self.toolButton_expand.setGeometry(QRect(1090, 3, 61, 30))
        self.toolButton_expand.setFont(font3)
        self.toolButton_expand.setStyleSheet(u"")
        self.comboBox_4 = QComboBox(self.centralwidget)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(631, 3, 181, 30))
        self.comboBox_4.setFont(font3)
        self.comboBox_4.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.comboBox_4.setFrame(False)
        self.tabWidget_3 = QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(10, 40, 1140, 774))
        self.tabWidget_3.setFont(font3)
        self.tabWidget_3.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget_3.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget_3.setDocumentMode(True)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.widget_graph_3 = QWidget(self.tab_7)
        self.widget_graph_3.setObjectName(u"widget_graph_3")
        self.widget_graph_3.setGeometry(QRect(0, 0, 1140, 792))
        self.widget_graph_3.setStyleSheet(u"\n"
"background-color: rgb(165, 187, 230);")
        self.widget_5 = QWidget(self.widget_graph_3)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(0, 0, 1140, 364))
        self.widget_5.setStyleSheet(u"background-color: rgb(131, 144, 186);")
        self.label_expense_record = QLabel(self.widget_5)
        self.label_expense_record.setObjectName(u"label_expense_record")
        self.label_expense_record.setGeometry(QRect(14, -4, 181, 31))
        self.label_expense_record.setFont(font)
        self.label_expense_record.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_total_expense = QLabel(self.widget_5)
        self.label_total_expense.setObjectName(u"label_total_expense")
        self.label_total_expense.setGeometry(QRect(740, 328, 231, 31))
        font4 = QFont()
        font4.setPointSize(16)
        self.label_total_expense.setFont(font4)
        self.label_total_expense.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_total_spends = QLabel(self.widget_5)
        self.label_total_spends.setObjectName(u"label_total_spends")
        self.label_total_spends.setGeometry(QRect(972, 333, 151, 21))
        self.label_total_spends.setFont(font4)
        self.label_total_spends.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tableWidget_1 = QTableWidget(self.widget_5)
        if (self.tableWidget_1.columnCount() < 7):
            self.tableWidget_1.setColumnCount(7)
        font5 = QFont()
        font5.setPointSize(9)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font5);
        self.tableWidget_1.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        if (self.tableWidget_1.rowCount() < 9):
            self.tableWidget_1.setRowCount(9)
        self.tableWidget_1.setObjectName(u"tableWidget_1")
        self.tableWidget_1.setGeometry(QRect(10, 27, 1121, 301))
        self.tableWidget_1.setFont(font4)
        self.tableWidget_1.setStyleSheet(u"background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(200, 207, 222);")
        self.tableWidget_1.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget_1.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_1.setLineWidth(1)
        self.tableWidget_1.setMidLineWidth(0)
        self.tableWidget_1.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget_1.setAlternatingRowColors(True)
        self.tableWidget_1.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableWidget_1.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_1.setTextElideMode(Qt.TextElideMode.ElideMiddle)
        self.tableWidget_1.setShowGrid(True)
        self.tableWidget_1.setGridStyle(Qt.PenStyle.DashLine)
        self.tableWidget_1.setSortingEnabled(False)
        self.tableWidget_1.setRowCount(9)
        self.tableWidget_1.setColumnCount(7)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_1.horizontalHeader().setMinimumSectionSize(41)
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_1.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_1.verticalHeader().setStretchLastSection(False)
        self.lineEdit_spend = QLineEdit(self.widget_5)
        self.lineEdit_spend.setObjectName(u"lineEdit_spend")
        self.lineEdit_spend.setGeometry(QRect(10, 333, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_spend.sizePolicy().hasHeightForWidth())
        self.lineEdit_spend.setSizePolicy(sizePolicy)
        self.lineEdit_spend.setMinimumSize(QSize(0, 0))
        self.lineEdit_spend.setMaximumSize(QSize(1920, 70))
        self.lineEdit_spend.setFont(font)
        self.lineEdit_spend.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_spend.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_spend.setMaxLength(1000)
        self.lineEdit_spend.setFrame(False)
        self.lineEdit_spend.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_spend.setCursorPosition(0)
        self.lineEdit_spend.setDragEnabled(True)
        self.lineEdit_spend.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_spend.setClearButtonEnabled(False)
        self.toolButton_save1 = QToolButton(self.widget_5)
        self.toolButton_save1.setObjectName(u"toolButton_save1")
        self.toolButton_save1.setGeometry(QRect(670, 333, 61, 26))
        self.toolButton_save1.setFont(font3)
        self.toolButton_save1.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_item = QLineEdit(self.widget_5)
        self.lineEdit_item.setObjectName(u"lineEdit_item")
        self.lineEdit_item.setGeometry(QRect(137, 333, 111, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_item.sizePolicy().hasHeightForWidth())
        self.lineEdit_item.setSizePolicy(sizePolicy)
        self.lineEdit_item.setMinimumSize(QSize(0, 0))
        self.lineEdit_item.setMaximumSize(QSize(1920, 70))
        self.lineEdit_item.setFont(font)
        self.lineEdit_item.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_item.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_item.setMaxLength(1000)
        self.lineEdit_item.setFrame(False)
        self.lineEdit_item.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_item.setCursorPosition(0)
        self.lineEdit_item.setDragEnabled(True)
        self.lineEdit_item.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_item.setClearButtonEnabled(False)
        self.lineEdit_reciepent = QLineEdit(self.widget_5)
        self.lineEdit_reciepent.setObjectName(u"lineEdit_reciepent")
        self.lineEdit_reciepent.setGeometry(QRect(253, 333, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_reciepent.sizePolicy().hasHeightForWidth())
        self.lineEdit_reciepent.setSizePolicy(sizePolicy)
        self.lineEdit_reciepent.setMinimumSize(QSize(0, 0))
        self.lineEdit_reciepent.setMaximumSize(QSize(1920, 70))
        self.lineEdit_reciepent.setFont(font)
        self.lineEdit_reciepent.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_reciepent.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_reciepent.setMaxLength(1000)
        self.lineEdit_reciepent.setFrame(False)
        self.lineEdit_reciepent.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_reciepent.setCursorPosition(0)
        self.lineEdit_reciepent.setDragEnabled(True)
        self.lineEdit_reciepent.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_reciepent.setClearButtonEnabled(False)
        self.toolButton_del_row = QToolButton(self.widget_5)
        self.toolButton_del_row.setObjectName(u"toolButton_del_row")
        self.toolButton_del_row.setGeometry(QRect(1072, 0, 60, 26))
        self.toolButton_del_row.setFont(font3)
        self.toolButton_del_row.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.label_expense_record.raise_()
        self.label_total_expense.raise_()
        self.label_total_spends.raise_()
        self.lineEdit_spend.raise_()
        self.toolButton_save1.raise_()
        self.lineEdit_item.raise_()
        self.lineEdit_reciepent.raise_()
        self.toolButton_del_row.raise_()
        self.tableWidget_1.raise_()
        self.widget_6 = QWidget(self.widget_graph_3)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(0, 370, 1140, 374))
        self.widget_6.setStyleSheet(u"background-color: rgb(131, 144, 186);")
        self.label_extra_gains = QLabel(self.widget_6)
        self.label_extra_gains.setObjectName(u"label_extra_gains")
        self.label_extra_gains.setGeometry(QRect(14, -4, 111, 31))
        self.label_extra_gains.setFont(font)
        self.label_extra_gains.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_monthly_gains = QLabel(self.widget_6)
        self.label_monthly_gains.setObjectName(u"label_monthly_gains")
        self.label_monthly_gains.setGeometry(QRect(740, 333, 201, 31))
        self.label_monthly_gains.setFont(font4)
        self.label_monthly_gains.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_total_gains = QLabel(self.widget_6)
        self.label_total_gains.setObjectName(u"label_total_gains")
        self.label_total_gains.setGeometry(QRect(950, 338, 171, 21))
        self.label_total_gains.setFont(font4)
        self.label_total_gains.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tableWidget_2 = QTableWidget(self.widget_6)
        if (self.tableWidget_2.columnCount() < 7):
            self.tableWidget_2.setColumnCount(7)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font5);
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, __qtablewidgetitem13)
        if (self.tableWidget_2.rowCount() < 12):
            self.tableWidget_2.setRowCount(12)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(10, 27, 1121, 306))
        self.tableWidget_2.setFont(font4)
        self.tableWidget_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tableWidget_2.setStyleSheet(u"background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(200, 207, 222);")
        self.tableWidget_2.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget_2.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setMidLineWidth(0)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(Qt.PenStyle.DashLine)
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setRowCount(12)
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(41)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.lineEdit_get = QLineEdit(self.widget_6)
        self.lineEdit_get.setObjectName(u"lineEdit_get")
        self.lineEdit_get.setGeometry(QRect(10, 339, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_get.sizePolicy().hasHeightForWidth())
        self.lineEdit_get.setSizePolicy(sizePolicy)
        self.lineEdit_get.setMinimumSize(QSize(0, 0))
        self.lineEdit_get.setMaximumSize(QSize(1920, 70))
        self.lineEdit_get.setFont(font)
        self.lineEdit_get.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_get.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_get.setMaxLength(1000)
        self.lineEdit_get.setFrame(False)
        self.lineEdit_get.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_get.setCursorPosition(0)
        self.lineEdit_get.setDragEnabled(True)
        self.lineEdit_get.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_get.setClearButtonEnabled(False)
        self.toolButton_save2 = QToolButton(self.widget_6)
        self.toolButton_save2.setObjectName(u"toolButton_save2")
        self.toolButton_save2.setGeometry(QRect(670, 338, 61, 26))
        self.toolButton_save2.setFont(font3)
        self.toolButton_save2.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_for_what = QLineEdit(self.widget_6)
        self.lineEdit_for_what.setObjectName(u"lineEdit_for_what")
        self.lineEdit_for_what.setGeometry(QRect(137, 339, 111, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_for_what.sizePolicy().hasHeightForWidth())
        self.lineEdit_for_what.setSizePolicy(sizePolicy)
        self.lineEdit_for_what.setMinimumSize(QSize(0, 0))
        self.lineEdit_for_what.setMaximumSize(QSize(1920, 70))
        self.lineEdit_for_what.setFont(font)
        self.lineEdit_for_what.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_for_what.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_for_what.setMaxLength(1000)
        self.lineEdit_for_what.setFrame(False)
        self.lineEdit_for_what.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_for_what.setCursorPosition(0)
        self.lineEdit_for_what.setDragEnabled(True)
        self.lineEdit_for_what.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_for_what.setClearButtonEnabled(False)
        self.lineEdit_giver = QLineEdit(self.widget_6)
        self.lineEdit_giver.setObjectName(u"lineEdit_giver")
        self.lineEdit_giver.setGeometry(QRect(253, 339, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_giver.sizePolicy().hasHeightForWidth())
        self.lineEdit_giver.setSizePolicy(sizePolicy)
        self.lineEdit_giver.setMinimumSize(QSize(0, 0))
        self.lineEdit_giver.setMaximumSize(QSize(1920, 70))
        self.lineEdit_giver.setFont(font)
        self.lineEdit_giver.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_giver.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_giver.setMaxLength(1000)
        self.lineEdit_giver.setFrame(False)
        self.lineEdit_giver.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_giver.setCursorPosition(0)
        self.lineEdit_giver.setDragEnabled(True)
        self.lineEdit_giver.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_giver.setClearButtonEnabled(False)
        self.toolButton_del_row_2 = QToolButton(self.widget_6)
        self.toolButton_del_row_2.setObjectName(u"toolButton_del_row_2")
        self.toolButton_del_row_2.setGeometry(QRect(1072, 0, 60, 26))
        self.toolButton_del_row_2.setFont(font3)
        self.toolButton_del_row_2.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.widget_graph_4 = QWidget(self.tab_8)
        self.widget_graph_4.setObjectName(u"widget_graph_4")
        self.widget_graph_4.setGeometry(QRect(0, 0, 1140, 774))
        self.widget_graph_4.setStyleSheet(u"background-color: rgb(40, 40, 40);")
        self.widget_7 = QWidget(self.widget_graph_4)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(0, 0, 1140, 757))
        self.widget_7.setStyleSheet(u"background-color: rgb(131, 144, 186);")
        self.label_extra_gains_2 = QLabel(self.widget_7)
        self.label_extra_gains_2.setObjectName(u"label_extra_gains_2")
        self.label_extra_gains_2.setGeometry(QRect(14, -4, 181, 31))
        self.label_extra_gains_2.setFont(font)
        self.label_extra_gains_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_monthly_gains_2 = QLabel(self.widget_7)
        self.label_monthly_gains_2.setObjectName(u"label_monthly_gains_2")
        self.label_monthly_gains_2.setGeometry(QRect(740, 715, 201, 31))
        self.label_monthly_gains_2.setFont(font4)
        self.label_monthly_gains_2.setStyleSheet(u"\n"
"color: rgb(0, 0, 0);")
        self.label_total_gains_2 = QLabel(self.widget_7)
        self.label_total_gains_2.setObjectName(u"label_total_gains_2")
        self.label_total_gains_2.setGeometry(QRect(950, 720, 171, 21))
        self.label_total_gains_2.setFont(font4)
        self.label_total_gains_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tableWidget_3 = QTableWidget(self.widget_7)
        if (self.tableWidget_3.columnCount() < 7):
            self.tableWidget_3.setColumnCount(7)
        __qtablewidgetitem14 = QTableWidgetItem()
        __qtablewidgetitem14.setFont(font5);
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, __qtablewidgetitem20)
        if (self.tableWidget_3.rowCount() < 23):
            self.tableWidget_3.setRowCount(23)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(10, 27, 1121, 687))
        self.tableWidget_3.setFont(font4)
        self.tableWidget_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tableWidget_3.setStyleSheet(u"background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(200, 207, 222);")
        self.tableWidget_3.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget_3.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_3.setLineWidth(1)
        self.tableWidget_3.setMidLineWidth(0)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableWidget_3.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setGridStyle(Qt.PenStyle.DashLine)
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setRowCount(23)
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(41)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.lineEdit_get_2 = QLineEdit(self.widget_7)
        self.lineEdit_get_2.setObjectName(u"lineEdit_get_2")
        self.lineEdit_get_2.setGeometry(QRect(12, 721, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_get_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_get_2.setSizePolicy(sizePolicy)
        self.lineEdit_get_2.setMinimumSize(QSize(0, 0))
        self.lineEdit_get_2.setMaximumSize(QSize(1920, 70))
        self.lineEdit_get_2.setFont(font)
        self.lineEdit_get_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_get_2.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_get_2.setMaxLength(1000)
        self.lineEdit_get_2.setFrame(False)
        self.lineEdit_get_2.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_get_2.setCursorPosition(0)
        self.lineEdit_get_2.setDragEnabled(True)
        self.lineEdit_get_2.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_get_2.setClearButtonEnabled(False)
        self.toolButton_save2_2 = QToolButton(self.widget_7)
        self.toolButton_save2_2.setObjectName(u"toolButton_save2_2")
        self.toolButton_save2_2.setGeometry(QRect(670, 719, 61, 26))
        self.toolButton_save2_2.setFont(font3)
        self.toolButton_save2_2.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_for_what_2 = QLineEdit(self.widget_7)
        self.lineEdit_for_what_2.setObjectName(u"lineEdit_for_what_2")
        self.lineEdit_for_what_2.setGeometry(QRect(137, 721, 111, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_for_what_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_for_what_2.setSizePolicy(sizePolicy)
        self.lineEdit_for_what_2.setMinimumSize(QSize(0, 0))
        self.lineEdit_for_what_2.setMaximumSize(QSize(1920, 70))
        self.lineEdit_for_what_2.setFont(font)
        self.lineEdit_for_what_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_for_what_2.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_for_what_2.setMaxLength(1000)
        self.lineEdit_for_what_2.setFrame(False)
        self.lineEdit_for_what_2.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_for_what_2.setCursorPosition(0)
        self.lineEdit_for_what_2.setDragEnabled(True)
        self.lineEdit_for_what_2.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_for_what_2.setClearButtonEnabled(False)
        self.lineEdit_giver_2 = QLineEdit(self.widget_7)
        self.lineEdit_giver_2.setObjectName(u"lineEdit_giver_2")
        self.lineEdit_giver_2.setGeometry(QRect(253, 721, 121, 25))
        sizePolicy.setHeightForWidth(self.lineEdit_giver_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_giver_2.setSizePolicy(sizePolicy)
        self.lineEdit_giver_2.setMinimumSize(QSize(0, 0))
        self.lineEdit_giver_2.setMaximumSize(QSize(1920, 70))
        self.lineEdit_giver_2.setFont(font)
        self.lineEdit_giver_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_giver_2.setStyleSheet(u"background-color: rgb(224, 224, 224);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_giver_2.setMaxLength(1000)
        self.lineEdit_giver_2.setFrame(False)
        self.lineEdit_giver_2.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_giver_2.setCursorPosition(0)
        self.lineEdit_giver_2.setDragEnabled(True)
        self.lineEdit_giver_2.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_giver_2.setClearButtonEnabled(False)
        self.toolButton_del_row_3 = QToolButton(self.widget_7)
        self.toolButton_del_row_3.setObjectName(u"toolButton_del_row_3")
        self.toolButton_del_row_3.setGeometry(QRect(1072, 0, 60, 26))
        self.toolButton_del_row_3.setFont(font3)
        self.toolButton_del_row_3.setStyleSheet(u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.widget_2 = QWidget(self.tab_10)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(0, 0, 1140, 775))
        self.widget_2.setStyleSheet(u"background-color: rgb(131, 144, 186);")
        self.widget_3 = QWidget(self.widget_2)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 104, 1120, 638))
        self.widget_3.setStyleSheet(u"\n"
"background-color: rgb(165, 187, 230);")
        self.listWidget_stock_list = QListWidget(self.widget_3)
        self.listWidget_stock_list.setObjectName(u"listWidget_stock_list")
        self.listWidget_stock_list.setGeometry(QRect(5, 35, 435, 565))
        self.listWidget_stock_list.setFont(font3)
        self.listWidget_stock_list.setStyleSheet(u"background-color: rgb(228, 235, 248);\n"
"color: rgb(0, 0, 0);")
        self.listWidget_stock_list.setSelectionRectVisible(True)
        self.tableWidget_item_table = QTableWidget(self.widget_3)
        if (self.tableWidget_item_table.columnCount() < 3):
            self.tableWidget_item_table.setColumnCount(3)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget_item_table.setHorizontalHeaderItem(0, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget_item_table.setHorizontalHeaderItem(1, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget_item_table.setHorizontalHeaderItem(2, __qtablewidgetitem23)
        if (self.tableWidget_item_table.rowCount() < 18):
            self.tableWidget_item_table.setRowCount(18)
        self.tableWidget_item_table.setObjectName(u"tableWidget_item_table")
        self.tableWidget_item_table.setGeometry(QRect(445, 35, 670, 565))
        self.tableWidget_item_table.setFont(font3)
        self.tableWidget_item_table.setStyleSheet(u"background-color: rgb(250, 250, 250);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(200, 207, 222);\n"
"selection-color: rgb(25, 163, 255);")
        self.tableWidget_item_table.setRowCount(18)
        self.pushButton_search_item_button_ = QPushButton(self.widget_3)
        self.pushButton_search_item_button_.setObjectName(u"pushButton_search_item_button_")
        self.pushButton_search_item_button_.setGeometry(QRect(780, 2, 61, 31))
        self.pushButton_search_item_button_.setFont(font3)
        self.pushButton_search_item_button_.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_search_item_lineedit = QLineEdit(self.widget_3)
        self.lineEdit_search_item_lineedit.setObjectName(u"lineEdit_search_item_lineedit")
        self.lineEdit_search_item_lineedit.setGeometry(QRect(550, 4, 225, 26))
        self.lineEdit_search_item_lineedit.setFont(font3)
        self.lineEdit_search_item_lineedit.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_24 = QLabel(self.widget_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(448, 6, 101, 21))
        self.label_24.setFont(font3)
        self.label_24.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_search_stock_input = QLineEdit(self.widget_3)
        self.lineEdit_search_stock_input.setObjectName(u"lineEdit_search_stock_input")
        self.lineEdit_search_stock_input.setGeometry(QRect(101, 4, 181, 26))
        self.lineEdit_search_stock_input.setFont(font3)
        self.lineEdit_search_stock_input.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_search_stock_button_ = QPushButton(self.widget_3)
        self.pushButton_search_stock_button_.setObjectName(u"pushButton_search_stock_button_")
        self.pushButton_search_stock_button_.setGeometry(QRect(285, 2, 61, 31))
        self.pushButton_search_stock_button_.setFont(font3)
        self.pushButton_search_stock_button_.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.widget_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(6, 6, 94, 21))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.pushButton_delete_item_button = QPushButton(self.widget_3)
        self.pushButton_delete_item_button.setObjectName(u"pushButton_delete_item_button")
        self.pushButton_delete_item_button.setGeometry(QRect(1056, 4, 60, 28))
        self.pushButton_delete_item_button.setFont(font3)
        self.pushButton_delete_item_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_delete_stock_button = QPushButton(self.widget_3)
        self.pushButton_delete_stock_button.setObjectName(u"pushButton_delete_stock_button")
        self.pushButton_delete_stock_button.setGeometry(QRect(382, 4, 60, 28))
        self.pushButton_delete_stock_button.setFont(font3)
        self.pushButton_delete_stock_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_add_item_button = QPushButton(self.widget_3)
        self.pushButton_add_item_button.setObjectName(u"pushButton_add_item_button")
        self.pushButton_add_item_button.setGeometry(QRect(980, 604, 101, 31))
        self.pushButton_add_item_button.setFont(font3)
        self.pushButton_add_item_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_item_rate_input = QLineEdit(self.widget_3)
        self.lineEdit_item_rate_input.setObjectName(u"lineEdit_item_rate_input")
        self.lineEdit_item_rate_input.setGeometry(QRect(490, 606, 181, 26))
        self.lineEdit_item_rate_input.setFont(font3)
        self.lineEdit_item_rate_input.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_12 = QLabel(self.widget_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 610, 81, 21))
        self.label_12.setFont(font3)
        self.label_12.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_item_quantity_input = QLineEdit(self.widget_3)
        self.lineEdit_item_quantity_input.setObjectName(u"lineEdit_item_quantity_input")
        self.lineEdit_item_quantity_input.setGeometry(QRect(780, 606, 191, 26))
        self.lineEdit_item_quantity_input.setFont(font3)
        self.lineEdit_item_quantity_input.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_16 = QLabel(self.widget_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(710, 608, 71, 21))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_15 = QLabel(self.widget_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(450, 608, 41, 21))
        self.label_15.setFont(font3)
        self.label_15.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_item_name_input = QLineEdit(self.widget_3)
        self.lineEdit_item_name_input.setObjectName(u"lineEdit_item_name_input")
        self.lineEdit_item_name_input.setGeometry(QRect(120, 606, 321, 26))
        self.lineEdit_item_name_input.setFont(font3)
        self.lineEdit_item_name_input.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.widget_4 = QWidget(self.widget_2)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(10, 27, 1120, 51))
        self.widget_4.setStyleSheet(u"background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_add_stock_button = QPushButton(self.widget_4)
        self.pushButton_add_stock_button.setObjectName(u"pushButton_add_stock_button")
        self.pushButton_add_stock_button.setGeometry(QRect(510, 10, 121, 31))
        self.pushButton_add_stock_button.setFont(font3)
        self.pushButton_add_stock_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_stock_name_input = QLineEdit(self.widget_4)
        self.lineEdit_stock_name_input.setObjectName(u"lineEdit_stock_name_input")
        self.lineEdit_stock_name_input.setGeometry(QRect(118, 13, 381, 26))
        self.lineEdit_stock_name_input.setFont(font3)
        self.lineEdit_stock_name_input.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_9 = QLabel(self.widget_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(18, 16, 91, 21))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.comboBox_5 = QComboBox(self.widget_4)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(890, 10, 221, 30))
        self.comboBox_5.setFont(font3)
        self.comboBox_5.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.comboBox_5.setFrame(False)
        self.label_extra_gains_3 = QLabel(self.widget_2)
        self.label_extra_gains_3.setObjectName(u"label_extra_gains_3")
        self.label_extra_gains_3.setGeometry(QRect(14, -2, 181, 25))
        self.label_extra_gains_3.setFont(font)
        self.label_extra_gains_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_23 = QLabel(self.widget_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(740, 80, 101, 21))
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_22 = QLabel(self.widget_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(190, 80, 71, 21))
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_load_button = QPushButton(self.widget_2)
        self.pushButton_load_button.setObjectName(u"pushButton_load_button")
        self.pushButton_load_button.setGeometry(QRect(1060, 0, 71, 28))
        self.pushButton_load_button.setFont(font3)
        self.pushButton_load_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_save_button = QPushButton(self.widget_2)
        self.pushButton_save_button.setObjectName(u"pushButton_save_button")
        self.pushButton_save_button.setGeometry(QRect(990, 0, 71, 28))
        self.pushButton_save_button.setFont(font3)
        self.pushButton_save_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.widget_8 = QWidget(self.tab_11)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(0, 0, 1141, 751))
        self.widget_8.setStyleSheet(u"background-color: rgb(131, 144, 186);")
        self.scrollArea_image_grid = QScrollArea(self.widget_8)
        self.scrollArea_image_grid.setObjectName(u"scrollArea_image_grid")
        self.scrollArea_image_grid.setGeometry(QRect(10, 40, 801, 701))
        self.scrollArea_image_grid.setStyleSheet(u"\n"
"background-color: rgb(165, 187, 230);")
        self.scrollArea_image_grid.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 799, 699))
        self.scrollArea_image_grid.setWidget(self.scrollAreaWidgetContents)
        self.label_image_show = QLabel(self.widget_8)
        self.label_image_show.setObjectName(u"label_image_show")
        self.label_image_show.setGeometry(QRect(820, 40, 310, 411))
        self.label_image_show.setFont(font)
        self.label_image_show.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_image_show.setAutoFillBackground(False)
        self.label_image_show.setStyleSheet(u"background-color: rgb(228, 235, 248);")
        self.label_image_show.setFrameShape(QFrame.Shape.Box)
        self.label_image_show.setScaledContents(False)
        self.textEdit_image_description = QTextEdit(self.widget_8)
        self.textEdit_image_description.setObjectName(u"textEdit_image_description")
        self.textEdit_image_description.setGeometry(QRect(819, 459, 311, 251))
        self.textEdit_image_description.setFont(font)
        self.textEdit_image_description.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.textEdit_image_description.setFrameShape(QFrame.Shape.WinPanel)
        self.label_25 = QLabel(self.widget_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(440, 2, 281, 31))
        font6 = QFont()
        font6.setPointSize(18)
        self.label_25.setFont(font6)
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_refresh_image_grid = QPushButton(self.widget_8)
        self.pushButton_refresh_image_grid.setObjectName(u"pushButton_refresh_image_grid")
        self.pushButton_refresh_image_grid.setGeometry(QRect(982, 6, 151, 28))
        self.pushButton_refresh_image_grid.setFont(font3)
        self.pushButton_refresh_image_grid.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_save_description = QPushButton(self.widget_8)
        self.pushButton_save_description.setObjectName(u"pushButton_save_description")
        self.pushButton_save_description.setGeometry(QRect(982, 716, 150, 28))
        self.pushButton_save_description.setFont(font3)
        self.pushButton_save_description.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_open_product_image = QPushButton(self.widget_8)
        self.pushButton_open_product_image.setObjectName(u"pushButton_open_product_image")
        self.pushButton_open_product_image.setGeometry(QRect(820, 6, 161, 28))
        self.pushButton_open_product_image.setFont(font3)
        self.pushButton_open_product_image.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_show_product_folder = QPushButton(self.widget_8)
        self.pushButton_show_product_folder.setObjectName(u"pushButton_show_product_folder")
        self.pushButton_show_product_folder.setGeometry(QRect(818, 716, 160, 28))
        self.pushButton_show_product_folder.setFont(font3)
        self.pushButton_show_product_folder.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.widget_graph_6 = QWidget(self.tab_4)
        self.widget_graph_6.setObjectName(u"widget_graph_6")
        self.widget_graph_6.setGeometry(QRect(0, 0, 1140, 774))
        self.widget_graph_6.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.lineEdit_shop_name = QLineEdit(self.widget_graph_6)
        self.lineEdit_shop_name.setObjectName(u"lineEdit_shop_name")
        self.lineEdit_shop_name.setGeometry(QRect(212, 50, 381, 24))
        self.lineEdit_shop_name.setFont(font3)
        self.lineEdit_shop_name.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_shop_address = QLineEdit(self.widget_graph_6)
        self.lineEdit_shop_address.setObjectName(u"lineEdit_shop_address")
        self.lineEdit_shop_address.setGeometry(QRect(212, 80, 581, 24))
        self.lineEdit_shop_address.setFont(font3)
        self.lineEdit_shop_address.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_shop_gstin = QLineEdit(self.widget_graph_6)
        self.lineEdit_shop_gstin.setObjectName(u"lineEdit_shop_gstin")
        self.lineEdit_shop_gstin.setGeometry(QRect(212, 109, 311, 24))
        self.lineEdit_shop_gstin.setFont(font3)
        self.lineEdit_shop_gstin.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_customer_name = QLineEdit(self.widget_graph_6)
        self.lineEdit_customer_name.setObjectName(u"lineEdit_customer_name")
        self.lineEdit_customer_name.setGeometry(QRect(212, 140, 381, 24))
        self.lineEdit_customer_name.setFont(font3)
        self.lineEdit_customer_name.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_customer_address = QLineEdit(self.widget_graph_6)
        self.lineEdit_customer_address.setObjectName(u"lineEdit_customer_address")
        self.lineEdit_customer_address.setGeometry(QRect(212, 170, 581, 24))
        self.lineEdit_customer_address.setFont(font3)
        self.lineEdit_customer_address.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_customer_gstin = QLineEdit(self.widget_graph_6)
        self.lineEdit_customer_gstin.setObjectName(u"lineEdit_customer_gstin")
        self.lineEdit_customer_gstin.setGeometry(QRect(212, 200, 311, 24))
        self.lineEdit_customer_gstin.setFont(font3)
        self.lineEdit_customer_gstin.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_3 = QLabel(self.widget_graph_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 50, 131, 21))
        self.label_3.setFont(font3)
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_4 = QLabel(self.widget_graph_6)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 80, 141, 21))
        self.label_4.setFont(font3)
        self.label_4.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_5 = QLabel(self.widget_graph_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 110, 131, 21))
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_6 = QLabel(self.widget_graph_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(70, 140, 121, 21))
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_7 = QLabel(self.widget_graph_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(70, 170, 131, 21))
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_8 = QLabel(self.widget_graph_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 200, 121, 21))
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.table_item_table = QTableWidget(self.widget_graph_6)
        if (self.table_item_table.columnCount() < 8):
            self.table_item_table.setColumnCount(8)
        __qtablewidgetitem24 = QTableWidgetItem()
        __qtablewidgetitem24.setBackground(QColor(191, 191, 191));
        self.table_item_table.setHorizontalHeaderItem(0, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        __qtablewidgetitem25.setBackground(QColor(158, 158, 158));
        self.table_item_table.setHorizontalHeaderItem(1, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        __qtablewidgetitem26.setBackground(QColor(191, 191, 191));
        self.table_item_table.setHorizontalHeaderItem(2, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        __qtablewidgetitem27.setBackground(QColor(158, 158, 158));
        self.table_item_table.setHorizontalHeaderItem(3, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        __qtablewidgetitem28.setBackground(QColor(191, 191, 191));
        self.table_item_table.setHorizontalHeaderItem(4, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        __qtablewidgetitem29.setBackground(QColor(158, 158, 158));
        self.table_item_table.setHorizontalHeaderItem(5, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        __qtablewidgetitem30.setBackground(QColor(191, 191, 191));
        self.table_item_table.setHorizontalHeaderItem(6, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        __qtablewidgetitem31.setBackground(QColor(158, 158, 158));
        self.table_item_table.setHorizontalHeaderItem(7, __qtablewidgetitem31)
        self.table_item_table.setObjectName(u"table_item_table")
        self.table_item_table.setGeometry(QRect(70, 240, 1001, 381))
        self.table_item_table.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.table_item_table.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.table_item_table.setRowCount(0)
        self.table_item_table.setColumnCount(8)
        self.toolButton_save_button = QToolButton(self.widget_graph_6)
        self.toolButton_save_button.setObjectName(u"toolButton_save_button")
        self.toolButton_save_button.setGeometry(QRect(1075, 2, 61, 31))
        self.toolButton_save_button.setFont(font3)
        self.toolButton_save_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(190, 190, 190);")
        self.toolButton_add_item_button = QToolButton(self.widget_graph_6)
        self.toolButton_add_item_button.setObjectName(u"toolButton_add_item_button")
        self.toolButton_add_item_button.setGeometry(QRect(962, 630, 111, 31))
        self.toolButton_add_item_button.setFont(font3)
        self.toolButton_add_item_button.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(190, 190, 190);")
        self.lineEdit_bank_name = QLineEdit(self.widget_graph_6)
        self.lineEdit_bank_name.setObjectName(u"lineEdit_bank_name")
        self.lineEdit_bank_name.setGeometry(QRect(70, 656, 346, 24))
        self.lineEdit_bank_name.setFont(font3)
        self.lineEdit_bank_name.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_account_number = QLineEdit(self.widget_graph_6)
        self.lineEdit_account_number.setObjectName(u"lineEdit_account_number")
        self.lineEdit_account_number.setGeometry(QRect(427, 656, 346, 24))
        self.lineEdit_account_number.setFont(font3)
        self.lineEdit_account_number.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_ifsc_code = QLineEdit(self.widget_graph_6)
        self.lineEdit_ifsc_code.setObjectName(u"lineEdit_ifsc_code")
        self.lineEdit_ifsc_code.setGeometry(QRect(70, 703, 346, 24))
        self.lineEdit_ifsc_code.setFont(font3)
        self.lineEdit_ifsc_code.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_branch = QLineEdit(self.widget_graph_6)
        self.lineEdit_branch.setObjectName(u"lineEdit_branch")
        self.lineEdit_branch.setGeometry(QRect(430, 703, 346, 24))
        self.lineEdit_branch.setFont(font3)
        self.lineEdit_branch.setStyleSheet(u"background-color: rgb(247, 247, 247);\n"
"color: rgb(0, 0, 0);")
        self.label_17 = QLabel(self.widget_graph_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(70, 634, 121, 21))
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_18 = QLabel(self.widget_graph_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(430, 630, 121, 21))
        self.label_18.setFont(font3)
        self.label_18.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_19 = QLabel(self.widget_graph_6)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(70, 680, 121, 21))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_20 = QLabel(self.widget_graph_6)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(430, 680, 121, 21))
        self.label_20.setFont(font3)
        self.label_20.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_21 = QLabel(self.widget_graph_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(460, 10, 241, 31))
        font7 = QFont()
        font7.setPointSize(22)
        self.label_21.setFont(font7)
        self.label_21.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_suggest_item = QLineEdit(self.widget_graph_6)
        self.lineEdit_suggest_item.setObjectName(u"lineEdit_suggest_item")
        self.lineEdit_suggest_item.setGeometry(QRect(960, 90, 113, 31))
        self.lineEdit_suggest_item.setFont(font3)
        self.lineEdit_suggest_item.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_suggest_quantity = QLineEdit(self.widget_graph_6)
        self.lineEdit_suggest_quantity.setObjectName(u"lineEdit_suggest_quantity")
        self.lineEdit_suggest_quantity.setGeometry(QRect(960, 130, 113, 31))
        self.lineEdit_suggest_quantity.setFont(font3)
        self.lineEdit_suggest_quantity.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_suggest_rate = QLineEdit(self.widget_graph_6)
        self.lineEdit_suggest_rate.setObjectName(u"lineEdit_suggest_rate")
        self.lineEdit_suggest_rate.setGeometry(QRect(960, 170, 113, 31))
        self.lineEdit_suggest_rate.setFont(font3)
        self.lineEdit_suggest_rate.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_suggest_qty = QLabel(self.widget_graph_6)
        self.label_suggest_qty.setObjectName(u"label_suggest_qty")
        self.label_suggest_qty.setGeometry(QRect(960, 50, 161, 31))
        self.label_suggest_qty.setFont(font3)
        self.label_suggest_qty.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.label_date = QLabel(self.centralwidget)
        self.label_date.setObjectName(u"label_date")
        self.label_date.setGeometry(QRect(932, 5, 151, 21))
        self.label_date.setFont(font)
        self.label_date.setStyleSheet(u"")
        form1.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.tabWidget.raise_()
        self.textEdit.raise_()
        self.label_name.raise_()
        self.label_income.raise_()
        self.label_expense.raise_()
        self.label_savings.raise_()
        self.label_gains.raise_()
        self.label_2.raise_()
        self.comboBox_3.raise_()
        self.tabWidget_2.raise_()
        self.toolButton_expand.raise_()
        self.label_13.raise_()
        self.lineEdit_income0.raise_()
        self.label_14.raise_()
        self.lineEdit_income.raise_()
        self.comboBox_4.raise_()
        self.tabWidget_3.raise_()
        self.lineEdit_calc.raise_()
        self.label_calc.raise_()
        self.label_date.raise_()
        self.menubar = QMenuBar(form1)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1500, 33))
        self.menubar.setFont(font4)
        self.menubar.setStyleSheet(u"background-color: rgb(121, 134, 172);\n"
"selection-background-color: rgb(165, 187, 230);\n"
"color: rgb(255, 255, 255);")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuExport = QMenu(self.menubar)
        self.menuExport.setObjectName(u"menuExport")
        self.menuSnap = QMenu(self.menubar)
        self.menuSnap.setObjectName(u"menuSnap")
        self.menuDark = QMenu(self.menubar)
        self.menuDark.setObjectName(u"menuDark")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setGeometry(QRect(691, 153, 161, 93))
        self.menuAbout.setFont(font3)
        form1.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuSnap.menuAction())
        self.menubar.addAction(self.menuDark.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionTable_Edit)
        self.menuEdit.addAction(self.actionClear_Data)
        self.menuEdit.addAction(self.actionArrange)
        self.menuExport.addAction(self.actionAs_CSV_Excel)
        self.menuSnap.addSeparator()
        self.menuSnap.addAction(self.action_screenshot)
        self.menuSnap.addAction(self.actionOpen_Directories)
        self.menuDark.addAction(self.actionLight)
        self.menuDark.addAction(self.actionDakr)
        self.menuAbout.addAction(self.actionInfo)

        self.retranslateUi(form1)

        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(form1)
    # setupUi

    def retranslateUi(self, form1):
        form1.setWindowTitle(QCoreApplication.translate("form1", u"Finance Flow v1.1", None))
        form1.setStyleSheet(QCoreApplication.translate("form1", u"color: rgb(0, 0, 0);", None))
        self.actionINR.setText(QCoreApplication.translate("form1", u"INR", None))
        self.actionOpen.setText(QCoreApplication.translate("form1", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("form1", u"Save Settings", None))
        self.actionSave_As.setText(QCoreApplication.translate("form1", u"Save Notes", None))
        self.actionExit.setText(QCoreApplication.translate("form1", u"Exit", None))
        self.action_screenshot.setText(QCoreApplication.translate("form1", u"ScreenShot", None))
        self.actionTable_Edit.setText(QCoreApplication.translate("form1", u"Table Edit", None))
        self.actionAs_CSV_Excel.setText(QCoreApplication.translate("form1", u"As CSV/Excel", None))
        self.actionOpen_Directories.setText(QCoreApplication.translate("form1", u"Open Directory", None))
        self.actionLight.setText(QCoreApplication.translate("form1", u"Light", None))
        self.actionDakr.setText(QCoreApplication.translate("form1", u"Dark", None))
        self.actionUSD.setText(QCoreApplication.translate("form1", u"USD", None))
        self.actionClear_Data.setText(QCoreApplication.translate("form1", u"Reset Data", None))
        self.actionRefresh.setText(QCoreApplication.translate("form1", u"Refresh", None))
        self.actionInfo.setText(QCoreApplication.translate("form1", u"Info", None))
        self.actionArrange.setText(QCoreApplication.translate("form1", u"Arrange", None))
        self.label.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("form1", u"Calender", None))
        self.textEdit_notes.setHtml(QCoreApplication.translate("form1", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit_notes.setPlaceholderText(QCoreApplication.translate("form1", u"Notes...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("form1", u"Notes", None))
        self.label_13.setText(QCoreApplication.translate("form1", u"Monthly Income:", None))
        self.textEdit.setHtml(QCoreApplication.translate("form1", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#000000;\"># Current Summary Report</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font"
                        "-size:11pt; color:#000000;\">1. Total Income</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">2. Total Expense</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">3. Net Savings</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">4. Extra Gains</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">5. Miscellaneous Expense</span></p></body></html>", None))
        self.label_name.setText(QCoreApplication.translate("form1", u"Abhishek Verma", None))
        self.label_income.setText(QCoreApplication.translate("form1", u"64000/-", None))
        self.label_expense.setText(QCoreApplication.translate("form1", u"45000", None))
        self.label_savings.setText(QCoreApplication.translate("form1", u"15000", None))
        self.label_gains.setText(QCoreApplication.translate("form1", u"4000", None))
        self.label_2.setText("")
        self.lineEdit_income.setText(QCoreApplication.translate("form1", u"0", None))
        self.lineEdit_income.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("form1", u"GST-Auto", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("form1", u"0% GST", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("form1", u"5% GST", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("form1", u"12% GST", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("form1", u"18% GST", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("form1", u"28% GST", None))

        self.lineEdit_calc.setText("")
        self.lineEdit_calc.setPlaceholderText(QCoreApplication.translate("form1", u"Use Numkeys...", None))
        self.label_calc.setText(QCoreApplication.translate("form1", u"Calc :", None))
        self.label_14.setText(QCoreApplication.translate("form1", u"Current Income:", None))
        self.lineEdit_income0.setText(QCoreApplication.translate("form1", u"0", None))
        self.lineEdit_income0.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("form1", u"Remaining income", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("form1", u"Extra Gains", None))
        self.toolButton_expand.setText(QCoreApplication.translate("form1", u"Layout", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("form1", u"Default WorkSpace", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("form1", u"Sales", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("form1", u"Purchase", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("form1", u"Stock", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("form1", u"Banking Transactions", None))

        self.label_expense_record.setText(QCoreApplication.translate("form1", u"Purchases :-", None))
        self.label_total_expense.setText(QCoreApplication.translate("form1", u"Total monthly Spend = ", None))
        self.label_total_spends.setText(QCoreApplication.translate("form1", u"0", None))
        ___qtablewidgetitem = self.tableWidget_1.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("form1", u"SPEND/-", None));
        ___qtablewidgetitem1 = self.tableWidget_1.horizontalHeaderItem(2)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("form1", u"Item/Purpose", None));
        ___qtablewidgetitem2 = self.tableWidget_1.horizontalHeaderItem(4)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("form1", u"Reciepent", None));
        ___qtablewidgetitem3 = self.tableWidget_1.horizontalHeaderItem(6)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("form1", u"Time", None));
        self.lineEdit_spend.setText("")
        self.lineEdit_spend.setPlaceholderText(QCoreApplication.translate("form1", u"Spend/-", None))
        self.toolButton_save1.setText(QCoreApplication.translate("form1", u"Entry", None))
        self.lineEdit_item.setText("")
        self.lineEdit_item.setPlaceholderText(QCoreApplication.translate("form1", u"Item...", None))
        self.lineEdit_reciepent.setText("")
        self.lineEdit_reciepent.setPlaceholderText(QCoreApplication.translate("form1", u"Recipient..", None))
        self.toolButton_del_row.setText(QCoreApplication.translate("form1", u"Delete", None))
        self.label_extra_gains.setText(QCoreApplication.translate("form1", u"Sales:-", None))
        self.label_monthly_gains.setText(QCoreApplication.translate("form1", u"Total monthly Sales = ", None))
        self.label_total_gains.setText(QCoreApplication.translate("form1", u"1600/-", None))
        ___qtablewidgetitem4 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("form1", u"RECIEVED/-", None));
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("form1", u"Item/N/A", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("form1", u"Payer/Giver", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(6)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("form1", u"Time", None));
        self.lineEdit_get.setText("")
        self.lineEdit_get.setPlaceholderText(QCoreApplication.translate("form1", u"Get/-", None))
        self.toolButton_save2.setText(QCoreApplication.translate("form1", u"Entry", None))
        self.lineEdit_for_what.setText("")
        self.lineEdit_for_what.setPlaceholderText(QCoreApplication.translate("form1", u"for what...", None))
        self.lineEdit_giver.setText("")
        self.lineEdit_giver.setPlaceholderText(QCoreApplication.translate("form1", u"Giver...", None))
        self.toolButton_del_row_2.setText(QCoreApplication.translate("form1", u"Delete", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("form1", u"Sales and Purchases", None))
        self.label_extra_gains_2.setText(QCoreApplication.translate("form1", u"Transaction Record:-", None))
        self.label_monthly_gains_2.setText(QCoreApplication.translate("form1", u"Total monthly Sales = ", None))
        self.label_total_gains_2.setText(QCoreApplication.translate("form1", u"1600/-", None))
        ___qtablewidgetitem8 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("form1", u"RECIEVED/-", None));
        ___qtablewidgetitem9 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("form1", u"Item/N/A", None));
        ___qtablewidgetitem10 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("form1", u"Payer/Giver", None));
        ___qtablewidgetitem11 = self.tableWidget_3.horizontalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("form1", u"Time", None));
        self.lineEdit_get_2.setText("")
        self.lineEdit_get_2.setPlaceholderText(QCoreApplication.translate("form1", u"Get/-", None))
        self.toolButton_save2_2.setText(QCoreApplication.translate("form1", u"Entry", None))
        self.lineEdit_for_what_2.setText("")
        self.lineEdit_for_what_2.setPlaceholderText(QCoreApplication.translate("form1", u"for what...", None))
        self.lineEdit_giver_2.setText("")
        self.lineEdit_giver_2.setPlaceholderText(QCoreApplication.translate("form1", u"Giver...", None))
        self.toolButton_del_row_3.setText(QCoreApplication.translate("form1", u"Delete", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("form1", u"Banking", None))
        ___qtablewidgetitem12 = self.tableWidget_item_table.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("form1", u"Name", None));
        ___qtablewidgetitem13 = self.tableWidget_item_table.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("form1", u"Rate (in Rs)", None));
        ___qtablewidgetitem14 = self.tableWidget_item_table.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("form1", u"Quantity", None));
        self.pushButton_search_item_button_.setText(QCoreApplication.translate("form1", u"Search", None))
        self.lineEdit_search_item_lineedit.setPlaceholderText(QCoreApplication.translate("form1", u"Search Items", None))
        self.label_24.setText(QCoreApplication.translate("form1", u"Search Items:", None))
        self.lineEdit_search_stock_input.setPlaceholderText(QCoreApplication.translate("form1", u"Search Stock", None))
        self.pushButton_search_stock_button_.setText(QCoreApplication.translate("form1", u"Search", None))
        self.label_10.setText(QCoreApplication.translate("form1", u"Search Stock:", None))
#if QT_CONFIG(tooltip)
        self.pushButton_delete_item_button.setToolTip(QCoreApplication.translate("form1", u"<html><head/><body><p>Shortcut: Del</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_delete_item_button.setText(QCoreApplication.translate("form1", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.pushButton_delete_item_button.setShortcut(QCoreApplication.translate("form1", u"Del", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_delete_stock_button.setToolTip(QCoreApplication.translate("form1", u"<html><head/><body><p>Shortcut: Ctrl+Del</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_delete_stock_button.setText(QCoreApplication.translate("form1", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.pushButton_delete_stock_button.setShortcut(QCoreApplication.translate("form1", u"Ctrl+Del", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_add_item_button.setText(QCoreApplication.translate("form1", u"Add Item", None))
        self.lineEdit_item_rate_input.setPlaceholderText(QCoreApplication.translate("form1", u"Enter Item Rate (Rs/-)", None))
        self.label_12.setText(QCoreApplication.translate("form1", u"Item Name:", None))
        self.lineEdit_item_quantity_input.setPlaceholderText(QCoreApplication.translate("form1", u"Enter Quantity (Default:1)", None))
        self.label_16.setText(QCoreApplication.translate("form1", u"Quantity:", None))
        self.label_15.setText(QCoreApplication.translate("form1", u"Rate:", None))
        self.lineEdit_item_name_input.setPlaceholderText(QCoreApplication.translate("form1", u"Enter Item Name", None))
        self.pushButton_add_stock_button.setText(QCoreApplication.translate("form1", u"Add Stock", None))
        self.lineEdit_stock_name_input.setPlaceholderText(QCoreApplication.translate("form1", u"Enter Stock Name", None))
        self.label_9.setText(QCoreApplication.translate("form1", u"Stock Name:", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("form1", u"Per Day", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("form1", u"Per Week", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("form1", u"Per Month", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("form1", u"Per Year", None))

        self.label_extra_gains_3.setText(QCoreApplication.translate("form1", u"Stock Details:-", None))
        self.label_23.setText(QCoreApplication.translate("form1", u"Stock Items", None))
        self.label_22.setText(QCoreApplication.translate("form1", u"Stocks", None))
        self.pushButton_load_button.setText(QCoreApplication.translate("form1", u"Refresh", None))
        self.pushButton_save_button.setText(QCoreApplication.translate("form1", u"Save", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), QCoreApplication.translate("form1", u"Stock Details", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), QCoreApplication.translate("form1", u"Company and Customer", None))
        self.label_image_show.setText(QCoreApplication.translate("form1", u"                 Product Image", None))
        self.textEdit_image_description.setPlaceholderText(QCoreApplication.translate("form1", u"Enter Product Description here...", None))
        self.label_25.setText(QCoreApplication.translate("form1", u"Products with Description", None))
        self.pushButton_refresh_image_grid.setText(QCoreApplication.translate("form1", u"Refresh", None))
        self.pushButton_save_description.setText(QCoreApplication.translate("form1", u"Save in Products", None))
        self.pushButton_open_product_image.setText(QCoreApplication.translate("form1", u"Open Product Image", None))
#if QT_CONFIG(shortcut)
        self.pushButton_open_product_image.setShortcut(QCoreApplication.translate("form1", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_show_product_folder.setText(QCoreApplication.translate("form1", u"Show Folder", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), QCoreApplication.translate("form1", u"Products", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("form1", u"Purchase Bill", None))
        self.lineEdit_shop_name.setPlaceholderText("")
        self.label_3.setText(QCoreApplication.translate("form1", u"Your Shop Name:", None))
        self.label_4.setText(QCoreApplication.translate("form1", u"Your Shop Address:", None))
        self.label_5.setText(QCoreApplication.translate("form1", u"Your Shop GSTIN:", None))
        self.label_6.setText(QCoreApplication.translate("form1", u"Customer Name:", None))
        self.label_7.setText(QCoreApplication.translate("form1", u"Customer Address:", None))
        self.label_8.setText(QCoreApplication.translate("form1", u"Customer GSTIN:", None))
        ___qtablewidgetitem15 = self.table_item_table.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("form1", u"Description", None));
        ___qtablewidgetitem16 = self.table_item_table.horizontalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("form1", u"HSN Code", None));
        ___qtablewidgetitem17 = self.table_item_table.horizontalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("form1", u"Quantity", None));
        ___qtablewidgetitem18 = self.table_item_table.horizontalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("form1", u"Rate", None));
        ___qtablewidgetitem19 = self.table_item_table.horizontalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("form1", u"GST Rate (%)", None));
        ___qtablewidgetitem20 = self.table_item_table.horizontalHeaderItem(5)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("form1", u"CGST", None));
        ___qtablewidgetitem21 = self.table_item_table.horizontalHeaderItem(6)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("form1", u"SGST", None));
        ___qtablewidgetitem22 = self.table_item_table.horizontalHeaderItem(7)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("form1", u"Total", None));
        self.toolButton_save_button.setText(QCoreApplication.translate("form1", u"Export", None))
        self.toolButton_add_item_button.setText(QCoreApplication.translate("form1", u"Add Item", None))
#if QT_CONFIG(shortcut)
        self.toolButton_add_item_button.setShortcut(QCoreApplication.translate("form1", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.label_17.setText(QCoreApplication.translate("form1", u"Bank Name:", None))
        self.label_18.setText(QCoreApplication.translate("form1", u"Account Number:", None))
        self.label_19.setText(QCoreApplication.translate("form1", u"IFSC Code:", None))
        self.label_20.setText(QCoreApplication.translate("form1", u"Branch:", None))
        self.label_21.setText(QCoreApplication.translate("form1", u"IINVOICE RECIEPT", None))
        self.lineEdit_suggest_item.setPlaceholderText(QCoreApplication.translate("form1", u"Type Item", None))
        self.lineEdit_suggest_quantity.setPlaceholderText(QCoreApplication.translate("form1", u"Qty", None))
        self.lineEdit_suggest_rate.setPlaceholderText(QCoreApplication.translate("form1", u"Rate", None))
        self.label_suggest_qty.setText(QCoreApplication.translate("form1", u"#Testing Total Quantity", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QCoreApplication.translate("form1", u"Sale Bill", None))
        self.label_date.setText(QCoreApplication.translate("form1", u"Date:- 26/01/2001", None))
        self.menuFile.setTitle(QCoreApplication.translate("form1", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("form1", u"Edit", None))
        self.menuExport.setTitle(QCoreApplication.translate("form1", u"Export", None))
        self.menuSnap.setTitle(QCoreApplication.translate("form1", u"Snap", None))
        self.menuDark.setTitle(QCoreApplication.translate("form1", u"Theme", None))
        self.menuAbout.setStyleSheet(QCoreApplication.translate("form1", u"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);", None))
        self.menuAbout.setTitle(QCoreApplication.translate("form1", u"About", None))
    # retranslateUi

