# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'introzbHoQD.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QSizePolicy, QToolButton, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(840, 395)
        Dialog.setMinimumSize(QSize(375, 395))
        Dialog.setMaximumSize(QSize(840, 395))
        self.lineEdit_company_name = QLineEdit(Dialog)
        self.lineEdit_company_name.setObjectName(u"lineEdit_company_name")
        self.lineEdit_company_name.setGeometry(QRect(384, 102, 411, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_company_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_company_name.setSizePolicy(sizePolicy)
        self.lineEdit_company_name.setMinimumSize(QSize(0, 0))
        self.lineEdit_company_name.setMaximumSize(QSize(1920, 70))
        font = QFont()
        font.setPointSize(14)
        self.lineEdit_company_name.setFont(font)
        self.lineEdit_company_name.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_company_name.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit_company_name.setMaxLength(1000)
        self.lineEdit_company_name.setFrame(False)
        self.lineEdit_company_name.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_company_name.setCursorPosition(0)
        self.lineEdit_company_name.setDragEnabled(True)
        self.lineEdit_company_name.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_company_name.setClearButtonEnabled(False)
        self.label_image = QLabel(Dialog)
        self.label_image.setObjectName(u"label_image")
        self.label_image.setGeometry(QRect(0, 40, 840, 356))
        self.label_image.setPixmap(QPixmap(u"back5.jpg"))
        self.label_image.setScaledContents(True)
        self.label_profile = QLabel(Dialog)
        self.label_profile.setObjectName(u"label_profile")
        self.label_profile.setGeometry(QRect(220, 75, 111, 111))
        self.label_profile.setPixmap(QPixmap(u"pprofile2.png"))
        self.label_profile.setScaledContents(True)
        self.label_trans = QLabel(Dialog)
        self.label_trans.setObjectName(u"label_trans")
        self.label_trans.setGeometry(QRect(377, 71, 424, 267))
        self.label_trans.setStyleSheet(u"background-color: rgba(31, 31, 31,0.8);")
        self.lineEdit_monthly_income = QLineEdit(Dialog)
        self.lineEdit_monthly_income.setObjectName(u"lineEdit_monthly_income")
        self.lineEdit_monthly_income.setGeometry(QRect(384, 230, 411, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_monthly_income.sizePolicy().hasHeightForWidth())
        self.lineEdit_monthly_income.setSizePolicy(sizePolicy)
        self.lineEdit_monthly_income.setMinimumSize(QSize(0, 0))
        self.lineEdit_monthly_income.setMaximumSize(QSize(1920, 70))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(False)
        self.lineEdit_monthly_income.setFont(font1)
        self.lineEdit_monthly_income.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.lineEdit_monthly_income.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_monthly_income.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.lineEdit_monthly_income.setMaxLength(1000)
        self.lineEdit_monthly_income.setFrame(False)
        self.lineEdit_monthly_income.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_monthly_income.setCursorPosition(0)
        self.lineEdit_monthly_income.setDragEnabled(True)
        self.lineEdit_monthly_income.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_monthly_income.setClearButtonEnabled(False)
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(386, 195, 161, 31))
        font2 = QFont()
        font2.setPointSize(16)
        self.label_13.setFont(font2)
        self.label_13.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(387, 258, 161, 31))
        self.label_14.setFont(font2)
        self.label_14.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.lineEdit_current_income = QLineEdit(Dialog)
        self.lineEdit_current_income.setObjectName(u"lineEdit_current_income")
        self.lineEdit_current_income.setGeometry(QRect(384, 290, 411, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_current_income.sizePolicy().hasHeightForWidth())
        self.lineEdit_current_income.setSizePolicy(sizePolicy)
        self.lineEdit_current_income.setMinimumSize(QSize(0, 0))
        self.lineEdit_current_income.setMaximumSize(QSize(1920, 70))
        self.lineEdit_current_income.setFont(font1)
        self.lineEdit_current_income.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.lineEdit_current_income.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_current_income.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.lineEdit_current_income.setMaxLength(1000)
        self.lineEdit_current_income.setFrame(False)
        self.lineEdit_current_income.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_current_income.setCursorPosition(0)
        self.lineEdit_current_income.setDragEnabled(True)
        self.lineEdit_current_income.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_current_income.setClearButtonEnabled(False)
        self.toolButton_Create = QToolButton(Dialog)
        self.toolButton_Create.setObjectName(u"toolButton_Create")
        self.toolButton_Create.setGeometry(QRect(690, 352, 111, 35))
        self.toolButton_Create.setFont(font2)
        self.toolButton_Create.setStyleSheet(u"background-color: rgb(98, 255, 156);\n"
"color: rgb(0, 0, 0);")
        self.widget = QWidget(Dialog)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 840, 80))
        self.widget.setStyleSheet(u"background-color: rgb(50, 50, 50);")
        self.label_21 = QLabel(self.widget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(330, 3, 181, 31))
        self.label_21.setFont(font2)
        self.label_21.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.lineEdit_show_name = QLineEdit(Dialog)
        self.lineEdit_show_name.setObjectName(u"lineEdit_show_name")
        self.lineEdit_show_name.setGeometry(QRect(384, 166, 411, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_show_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_show_name.setSizePolicy(sizePolicy)
        self.lineEdit_show_name.setMinimumSize(QSize(0, 0))
        self.lineEdit_show_name.setMaximumSize(QSize(1920, 70))
        self.lineEdit_show_name.setFont(font1)
        self.lineEdit_show_name.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.lineEdit_show_name.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_show_name.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit_show_name.setMaxLength(1000)
        self.lineEdit_show_name.setFrame(False)
        self.lineEdit_show_name.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_show_name.setCursorPosition(0)
        self.lineEdit_show_name.setDragEnabled(True)
        self.lineEdit_show_name.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_show_name.setClearButtonEnabled(False)
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(385, 133, 131, 31))
        self.label_16.setFont(font2)
        self.label_16.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(383, 67, 171, 31))
        self.label_17.setFont(font2)
        self.label_17.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.lineEdit_contact_no = QLineEdit(Dialog)
        self.lineEdit_contact_no.setObjectName(u"lineEdit_contact_no")
        self.lineEdit_contact_no.setGeometry(QRect(21, 343, 334, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_contact_no.sizePolicy().hasHeightForWidth())
        self.lineEdit_contact_no.setSizePolicy(sizePolicy)
        self.lineEdit_contact_no.setMinimumSize(QSize(0, 0))
        self.lineEdit_contact_no.setMaximumSize(QSize(1920, 70))
        self.lineEdit_contact_no.setFont(font1)
        self.lineEdit_contact_no.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_contact_no.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit_contact_no.setMaxLength(1000)
        self.lineEdit_contact_no.setFrame(False)
        self.lineEdit_contact_no.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_contact_no.setCursorPosition(0)
        self.lineEdit_contact_no.setDragEnabled(True)
        self.lineEdit_contact_no.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_contact_no.setClearButtonEnabled(False)
        self.label_18 = QLabel(Dialog)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(23, 308, 161, 31))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.label_19 = QLabel(Dialog)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(22, 246, 161, 31))
        self.label_19.setFont(font2)
        self.label_19.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.lineEdit_gmail = QLineEdit(Dialog)
        self.lineEdit_gmail.setObjectName(u"lineEdit_gmail")
        self.lineEdit_gmail.setGeometry(QRect(21, 279, 334, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_gmail.sizePolicy().hasHeightForWidth())
        self.lineEdit_gmail.setSizePolicy(sizePolicy)
        self.lineEdit_gmail.setMinimumSize(QSize(0, 0))
        self.lineEdit_gmail.setMaximumSize(QSize(1920, 70))
        self.lineEdit_gmail.setFont(font1)
        self.lineEdit_gmail.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_gmail.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit_gmail.setMaxLength(1000)
        self.lineEdit_gmail.setFrame(False)
        self.lineEdit_gmail.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_gmail.setCursorPosition(0)
        self.lineEdit_gmail.setDragEnabled(True)
        self.lineEdit_gmail.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_gmail.setClearButtonEnabled(False)
        self.label_20 = QLabel(Dialog)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 180, 131, 31))
        self.label_20.setFont(font2)
        self.label_20.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.lineEdit_admin_name = QLineEdit(Dialog)
        self.lineEdit_admin_name.setObjectName(u"lineEdit_admin_name")
        self.lineEdit_admin_name.setGeometry(QRect(21, 215, 334, 31))
        sizePolicy.setHeightForWidth(self.lineEdit_admin_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_admin_name.setSizePolicy(sizePolicy)
        self.lineEdit_admin_name.setMinimumSize(QSize(0, 0))
        self.lineEdit_admin_name.setMaximumSize(QSize(1920, 70))
        self.lineEdit_admin_name.setFont(font)
        self.lineEdit_admin_name.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_admin_name.setStyleSheet(u"background-color: rgb(49, 49, 49);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit_admin_name.setMaxLength(1000)
        self.lineEdit_admin_name.setFrame(False)
        self.lineEdit_admin_name.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit_admin_name.setCursorPosition(0)
        self.lineEdit_admin_name.setDragEnabled(True)
        self.lineEdit_admin_name.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_admin_name.setClearButtonEnabled(False)
        self.label_contact_no = QLabel(Dialog)
        self.label_contact_no.setObjectName(u"label_contact_no")
        self.label_contact_no.setGeometry(QRect(6, 47, 361, 341))
        self.label_contact_no.setStyleSheet(u"background-color: rgba(31, 31, 31, 0.9);")
        self.toolButton_set_image = QToolButton(Dialog)
        self.toolButton_set_image.setObjectName(u"toolButton_set_image")
        self.toolButton_set_image.setGeometry(QRect(324, 180, 26, 26))
        self.toolButton_set_image.setFont(font2)
        self.toolButton_set_image.setStyleSheet(u"background-color: rgb(137, 143, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 60, 201, 31))
        self.label_15.setFont(font2)
        self.label_15.setStyleSheet(u"color: rgb(83, 255, 206);")
        self.widget.raise_()
        self.label_image.raise_()
        self.label_trans.raise_()
        self.lineEdit_company_name.raise_()
        self.lineEdit_monthly_income.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lineEdit_current_income.raise_()
        self.toolButton_Create.raise_()
        self.lineEdit_show_name.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_contact_no.raise_()
        self.label_profile.raise_()
        self.label_20.raise_()
        self.lineEdit_admin_name.raise_()
        self.label_19.raise_()
        self.lineEdit_gmail.raise_()
        self.lineEdit_contact_no.raise_()
        self.label_18.raise_()
        self.toolButton_set_image.raise_()
        self.label_15.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.lineEdit_company_name.setText("")
        self.lineEdit_company_name.setPlaceholderText(QCoreApplication.translate("Dialog", u"pvt ltd...", None))
        self.label_image.setText("")
        self.label_profile.setText("")
        self.label_trans.setText("")
        self.lineEdit_monthly_income.setText("")
        self.lineEdit_monthly_income.setPlaceholderText(QCoreApplication.translate("Dialog", u"monthly/-", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Monthly Income:", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Current Income:", None))
        self.lineEdit_current_income.setText("")
        self.lineEdit_current_income.setPlaceholderText(QCoreApplication.translate("Dialog", u"current/-", None))
        self.toolButton_Create.setText(QCoreApplication.translate("Dialog", u"Create", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Finance Flow v1.1", None))
        self.lineEdit_show_name.setText("")
        self.lineEdit_show_name.setPlaceholderText(QCoreApplication.translate("Dialog", u"ex- groccery store", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Shop Name:", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Company Name:", None))
        self.lineEdit_contact_no.setText("")
        self.lineEdit_contact_no.setPlaceholderText(QCoreApplication.translate("Dialog", u"+91", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Contact No:", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Gmail", None))
        self.lineEdit_gmail.setText("")
        self.lineEdit_gmail.setPlaceholderText(QCoreApplication.translate("Dialog", u"abc@gmail.com", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Admin Name:", None))
        self.lineEdit_admin_name.setText("")
        self.lineEdit_admin_name.setPlaceholderText(QCoreApplication.translate("Dialog", u"admin...", None))
        self.label_contact_no.setText("")
        self.toolButton_set_image.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Create the Company", None))
    # retranslateUi

